package fortscale.domain.core;

public enum ActiveDirectoryOperationType {
    ACCOUNT_MANAGEMENT,
    PASSWORD_CHANGED,
    PASSWORD_CHANGED_BY_NON_OWNER,
    GROUP_MEMBERSHIP,
    USER_ACCOUNT_ENABLED,
    USER_ACCOUNT_DISABLED,
    USER_ACCOUNT_UNLOCKED,
    USER_ACCOUNT_TYPE_CHANGED,
    USER_ACCOUNT_RE_ENABLED,
    USER_ACCOUNT_LOCKED,
    USER_PASSWORD_NEVER_EXPIRES_OPTION_CHANGED,
    NESTED_MEMBER_ADDED_TO_CRITICAL_ENTERPRISE_GROUP,
    MEMBER_ADDED_TO_CRITICAL_ENTERPRISE_GROUP;
}
