package fortscale.domain.core;

/**
 * Created by alexp on 09-Jul-17.
 */
public enum FileOperationType {
    FOLDER_OPENED,
    FILE_DELETED,
    FILE_OPENED,
    FILE_RENAMED,
    FILE_MOVED,
    LOCAL_SHARE_PERMISSIONS_CHANGED,
    FOLDER_ACCESS_RIGHTS_CHANGED,
    FILE_ACCESS_RIGHTS_CHANGED,
    FILE_CLASSIFICATION_CHANGED,
    FOLDER_CLASSIFICATION_CHANGED,
    FILE_CENTRAL_ACCESS_POLICY_CHANGED;
}
