export const GET_RAR_INSTALLER_ID = 'ENDPOINT_RAR::GET_RAR_INSTALLER_ID';
export const SET_SERVER_ID = 'ENDPOINT_RAR::SET_SERVER_ID';
export const GET_AND_SAVE_RAR_CONFIG = 'ENDPOINT_RAR::GET_AND_SAVE_RAR_CONFIG';
export const RESET_RAR_CONFIG = 'ENDPOINT_RAR::RESET_RAR_CONFIG';
export const UPDATE_UI_STATE = 'ENDPOINT_RAR::UPDATE_UI_STATE';
export const TEST_RAR_CONFIG = 'ENDPOINT_RAR::TEST_RAR_CONFIG';
export const GET_AND_SAVE_ENABLE_STATUS = 'ENDPOINT_RAR::GET_AND_SAVE_ENABLE_STATUS';