// Actions Types for Searching Incidents in Add-To-Incident Modal
export const UPDATE_SEARCH_INCIDENTS_TEXT = 'INCIDENT::UPDATE_SEARCH_INCIDENTS_TEXT';
export const UPDATE_SEARCH_INCIDENTS_SORTBY = 'INCIDENT::UPDATE_SEARCH_INCIDENTS_SORTBY';
export const SEARCH_INCIDENTS_SELECT = 'INCIDENT::SEARCH_INCIDENTS_SELECT';
export const SEARCH_INCIDENTS_STARTED = 'INCIDENT::SEARCH_INCIDENTS_STARTED';
export const SEARCH_INCIDENTS_STREAM_INITIALIZED = 'INCIDENT::SEARCH_INCIDENTS_STREAM_INITIALIZED';
export const SEARCH_INCIDENTS_COMPLETED = 'INCIDENT::SEARCH_INCIDENTS_COMPLETED';
export const SEARCH_INCIDENTS_RETRIEVE_BATCH = 'INCIDENT::SEARCH_INCIDENTS_RETRIEVE_BATCH';
export const SEARCH_INCIDENTS_ERROR = 'INCIDENT::SEARCH_INCIDENTS_ERROR';
export const CLEAR_SEARCH_INCIDENTS_RESULTS = 'INCIDENT::CLEAR_SEARCH_INCIDENTS_RESULTS';

// Actions Types for Priority, category & Assignee Options in Create-Incident Modal
export const FETCH_ALL_ENABLED_USERS = 'RESPOND::FETCH_ALL_ENABLED_USERS';
export const FETCH_PRIORITY_TYPES = 'RESPOND::FETCH_PRIORITY_TYPES';
export const FETCH_CATEGORY_TAGS = 'RESPOND::FETCH_CATEGORY_TAGS';

// Actions Types for Add-To-Incident
export const ALERTS_ADD_TO_INCIDENT = 'RESPOND::ALERTS_ADD_TO_INCIDENT';
export const EVENTS_ADD_TO_INCIDENT = 'INVESTIGATE_EVENTS::EVENTS_ADD_TO_INCIDENT';

// Actions Types for Create-Incident
export const CREATE_INCIDENT_FROM_ALERTS = 'RESPOND::CREATE_INCIDENT';
export const CREATE_INCIDENT_FROM_EVENTS = 'INVESTIGATE_EVENTS::CREATE_INCIDENT';

// Actions Types to update alerts incidentId
export const UPDATE_INCIDENT_ON_ADD = 'RESPOND::UPDATE_INCIDENT_ON_ADD';
export const UPDATE_INCIDENT_ON_CREATE = 'RESPOND::UPDATE_INCIDENT_ON_CREATE';