
// Live Search Content Selections
export const RESOURCE_TOGGLE_SELECT = 'LIVE_CONTENT::RESOURCE_TOGGLE_SELECT';
export const RESOURCE_SELECT = 'LIVE_CONTENT::RESOURCE_SELECT';
export const RESOURCE_DESELECT = 'LIVE_CONTENT::RESOURCE_DESELECT';

// Live Search Criteria
export const UPDATE_SEARCH_CRITERIA = 'LIVE_CONTENT::UPDATE_SEARCH_CRITERIA';
export const RESET_SEARCH_CRITERIA = 'LIVE_CONTENT::RESET_SEARCH_CRITERIA';
export const GO_TO_FIRST_PAGE = 'LIVE_CONTENT::GO_TO_FIRST_PAGE';
export const GO_TO_LAST_PAGE = 'LIVE_CONTENT::GO_TO_LAST_PAGE';
export const GO_TO_NEXT_PAGE = 'LIVE_CONTENT::GO_TO_NEXT_PAGE';
export const GO_TO_PREVIOUS_PAGE = 'LIVE_CONTENT::GO_TO_PREVIOUS_PAGE';


// LIVE SEARCH DATA ACTION TYPES

// Dictionaries
export const FETCH_RESOURCE_TYPES = 'LIVE_CONTENT::FETCH_RESOURCE_TYPES';
export const FETCH_MEDIA = 'LIVE_CONTENT::FETCH_MEDIA';
export const FETCH_META_KEYS = 'LIVE_CONTENT::FETCH_META_KEYS';
export const FETCH_META_VALUES = 'LIVE_CONTENT::FETCH_META_VALUES';
export const FETCH_CATEGORIES = 'LIVE_CONTENT::FETCH_CATEGORIES';

// SEARCH
export const FETCH_SEARCH_RESULTS_STARTED = 'LIVE_CONTENT::FETCH_SEARCH_RESULTS_STARTED';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'LIVE_CONTENT::FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_FAILURE = 'LIVE_CONTENT::FETCH_SEARCH_RESULTS_FAILURE';

// UI State
export const FOCUS_RESOURCE = 'LIVE_CONTENT::FOCUS_RESOURCE';
export const BLUR_RESOURCE = 'LIVE_CONTENT::BLUR_RESOURCE';
