export const SET_EVENTS = 'PROCESS_ANALYSIS::SET_EVENTS';
export const SET_SELECTED_EVENTS = 'PROCESS_ANALYSIS::SET_SELECTED_EVENTS';
export const GET_EVENT_COUNT = 'PROCESS_ANALYSIS::GET_EVENT_COUNT';
export const SET_PROCESS_ANALYSIS_INPUT = 'PROCESS_ANALYSIS::SET_PROCESS_ANALYSIS_INPUT';
export const COMPLETED_EVENTS_STREAMING = 'PROCESS_ANALYSIS::COMPLETED_EVENTS_STREAMING';
export const INIT_EVENTS_STREAMING = 'PROCESS_ANALYSIS::INIT_EVENTS_STREAMING';
export const SET_EVENTS_PAGE_ERROR = 'PROCESS_ANALYSIS::SET_EVENTS_PAGE_ERROR';
export const SET_SORT_FIELD = 'PROCESS_ANALYSIS::SET_SORT_FIELD';

// process-properties
export const FETCH_PROCESS_PROPERTIES = 'PROCESS_ANALYSIS::FETCH_PROCESS_PROPERTIES';
export const RETRIEVE_FAILURE = 'PROCESS_ANALYSIS::RETRIEVE_FAILURE';

export const GET_EVENTS_COUNT_SAGA = 'PROCESS_ANALYSIS::GET_EVENTS_COUNT_SAGA';
export const SET_EVENTS_COUNT = 'PROCESS_ANALYSIS::SET_EVENTS_COUNT';
export const SET_EVENTS_COUNT_FAILED = 'PROCESS_ANALYSIS::SET_EVENTS_COUNT_FAILED';
export const SET_SELECTED_PROCESS = 'PROCESS_ANALYSIS::SET_SELECTED_PROCESS';
export const SET_NODE_PATH = 'PROCESS_ANALYSIS::SET_NODE_PATH';

export const SERVICES_RETRIEVE = 'PROCESS_ANALYSIS::SERVICES_RETRIEVE';
export const SUMMARY_RETRIEVE = 'PROCESS_ANALYSIS::SUMMARY_RETRIEVE';
export const SERVICE_SELECTED = 'PROCESS_ANALYSIS::SERVICE_SELECTED';
export const SET_QUERY_TIME_RANGE = 'PROCESS_ANALYSIS::SET_QUERY_TIME_RANGE';

// process-visuals

export const SET_DETAILS_TAB = 'PROCESS_ANALYSIS::SET_DETAILS_TAB';

// process-filter

export const UPDATE_FILTER_ITEMS = 'PROCESS_ANALYSIS::UPDATE_FILTER_ITEMS';
export const RESET_FILTER_ITEMS = 'PROCESS_ANALYSIS::RESET_FILTER_ITEMS';
