export const SET_EVENTS = 'PROCESS_ANALYSIS::SET_EVENTS';
export const GET_EVENT_COUNT = 'PROCESS_ANALYSIS::GET_EVENT_COUNT';
export const SET_PROCESS_ANALYSIS_INPUT = 'PROCESS_ANALYSIS::SET_PROCESS_ANALYSIS_INPUT';
export const COMPLETED_EVENTS_STREAMING = 'PROCESS_ANALYSIS::COMPLETED_EVENTS_STREAMING';
export const INIT_EVENTS_STREAMING = 'PROCESS_ANALYSIS::INIT_EVENTS_STREAMING';
export const SET_EVENTS_PAGE_ERROR = 'PROCESS_ANALYSIS::SET_EVENTS_PAGE_ERROR';

// process-properties
export const FETCH_PROCESS_PROPERTIES = 'PROCESS_ANALYSIS::FETCH_PROCESS_PROPERTIES';
export const RETRIEVE_FAILURE = 'PROCESS_ANALYSIS::RETRIEVE_FAILURE';

export const GET_EVENTS_COUNT_SAGA = 'PROCESS_ANALYSIS::GET_EVENTS_COUNT_SAGA';
export const SET_EVENTS_COUNT = 'PROCESS_ANALYSIS::SET_EVENTS_COUNT';
export const SET_EVENTS_COUNT_FAILED = 'PROCESS_ANALYSIS::SET_EVENTS_COUNT_FAILED';
export const SET_SELECTED_PROCESS = 'PROCESS_ANALYSIS::SET_SELECTED_PROCESS';
export const SET_NODE_PATH = 'PROCESS_ANALYSIS::SET_NODE_PATH';

// process-visuals

export const SET_DETAILS_TAB = 'PROCESS_ANALYSIS::SET_DETAILS_TAB';
