export const INITIALIZE_LIST_MANAGER = 'LIST_MANAGER::INITIALIZE_LIST_MANAGER';
export const SET_HIGHLIGHTED_INDEX = 'LIST_MANAGER::SET_HIGHLIGHTED_INDEX';
export const TOGGLE_LIST_VISIBILITY = 'LIST_MANAGER::TOGGLE_LIST_VISIBILITY';
export const SET_FILTER_TEXT = 'LIST_MANAGER::SET_FILTER_TEXT';
