// INIT
export const INITIALIZE_LIST_MANAGER = 'LIST_MANAGER::INITIALIZE_LIST_MANAGER';

// VISUAL
export const SET_HIGHLIGHTED_INDEX = 'LIST_MANAGER::SET_HIGHLIGHTED_INDEX';
export const SET_VIEW_NAME = 'LIST_MANAGER::SET_VIEW_NAME';
export const TOGGLE_LIST_VISIBILITY = 'LIST_MANAGER::TOGGLE_LIST_VISIBILITY';

// FILTER
export const SET_FILTER_TEXT = 'LIST_MANAGER::SET_FILTER_TEXT';

// ITEM
export const SET_SELECTED_ITEM_ID = 'LIST_MANAGER::SET_SELECTED_ITEM_ID';
export const EDIT_ITEM = 'LIST_MANAGER::EDIT_ITEM';
