export const INITIALIZE_LIST_MANAGER = 'LIST_MANAGER::INITIALIZE_LIST_MANAGER';
export const SET_LOCATION = 'LIST_MANAGER::SET_LOCATION';
export const SET_HIGHLIGHTED_INDEX = 'LIST_MANAGER::SET_HIGHLIGHTED_INDEX';
