export const TOGGLE_PREFERENCES_PANEL = 'PREFERENCES::TOGGLE_PREFERENCES_PANEL';
export const CLOSE_PREFERENCES_PANEL = 'PREFERENCES::CLOSE_PREFERENCES_PANEL';
export const RESET_PREFERENCES_PANEL = 'PREFERENCES::RESET_PREFERENCES_PANEL';