export const TOGGLE_PREFERENCES_PANEL = 'PREFERENCES::TOGGLE_PREFERENCES_PANEL';
export const CLOSE_PREFERENCES_PANEL = 'PREFERENCES::CLOSE_PREFERENCES_PANEL';
export const RESET_PREFERENCES_PANEL = 'PREFERENCES::RESET_PREFERENCES_PANEL';
export const LOAD_PREFERENCES = 'PREFERENCES::LOAD_PREFERENCES';
export const LOAD_PREFERENCES_ERROR = 'PREFERENCES::LOAD_PREFERENCES_ERROR';
export const SAVE_PREFERENCES = 'PREFERENCES::SAVE_PREFERENCES';
export const SAVE_PREFERENCES_INIT = 'PREFERENCES::SAVE_PREFERENCES_INIT';