export const INITIATE_ENTITY = 'ENTITY_DETAILS::INITIATE_ENTITY';
export const INITIATE_ALERT = 'ENTITY_DETAILS::INITIATE_ALERT';
export const INITIATE_INDICATOR = 'ENTITY_DETAILS::INITIATE_INDICATOR';
export const GET_ENTITY_DETAILS = 'ENTITY_DETAILS::GET_ENTITY_DETAILS';
export const RESET_ENTITY = 'ENTITY_DETAILS::RESET_ENTITY';
export const RESET_ALERT = 'ENTITY_DETAILS::RESET_ALERT';
export const RESET_INDICATOR = 'ENTITY_DETAILS::RESET_INDICATOR';