
// Endpoint server
export const ENDPOINT_SERVER_SELECTED = 'ENDPOINT::ENDPOINT_SERVER_SELECTED';
export const LIST_OF_ENDPOINT_SERVERS = 'ENDPOINT::LIST_OF_ENDPOINT_SERVERS';
export const ENDPOINT_SERVER_STATUS = 'ENDPOINT::ENDPOINT_SERVER_STATUS';
export const SET_QUERY_INPUT = 'ENDPOINT::SET_QUERY_INPUT';