// Visual action types
export const TOGGLE_HEADER = 'TOGGLE_HEADER';
export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';
export const TOGGLE_RESPONSE = 'TOGGLE_RESPONSE';
export const TOGGLE_META = 'TOGGLE_META';
export const TOGGLE_RECON_EXPANDED = 'TOGGLE_RECON_EXPANDED';
export const CLOSE_RECON = 'CLOSE_RECON';
export const INITIALIZE = 'INITIALIZE';

// Data action types
export const CHANGE_RECON_VIEW = 'CHANGE_RECON_VIEW';
export const LANGUAGE_RETRIEVE_SUCCESS = 'LANGUAGE_RETRIEVE_SUCCESS';
export const ALIASES_RETRIEVE_SUCCESS = 'ALIASES_RETRIEVE_SUCCESS';
export const META_RETRIEVE_SUCCESS = 'META_RETRIEVE_SUCCESS';
export const META_RETRIEVE_FAILURE = 'META_RETRIEVE_FAILURE';
export const SUMMARY_RETRIEVE_SUCCESS = 'SUMMARY_RETRIEVE_SUCCESS';
export const SUMMARY_RETRIEVE_FAILURE = 'SUMMARY_RETRIEVE_FAILURE';

// Content action types
export const RECON_FILES_RETRIEVE_SUCCESS = 'RECON_FILES_RETRIEVE_SUCCESS';
export const RECON_PACKETS_RETRIEVE_PAGE = 'RECON_PACKETS_RETRIEVE_PAGE';
export const RECON_CONTENT_RETRIEVE_FAILURE = 'RECON_CONTENT_RETRIEVE_FAILURE';

// In progress action types
export const RECON_CONTENT_RETRIEVE_STARTED = 'RECON_CONTENT_RETRIEVE_STARTED';
export const META_RETRIEVE_STARTED = 'META_RETRIEVE_STARTED';

// User interaction
export const RECON_FILES_FILE_TOGGLED = 'RECON_FILES_FILE_TOGGLED';
export const RECON_FILE_DOWNLOAD_SUCCESS = 'RECON_FILE_DOWNLOAD_SUCCESS';
