export default [
  'System',
  'Security',
  'Application',
  'Setup',
  'Forefront',
  'Forefront Endpoint Protection',
  'MSExchange',
  'LOGbndEX',
  'MSExchange Management_1_MSExchange CmdletLogs',
  'Exchange Auditing',
  'Microsoft-Exchange-MailboxDatabaseFailureItems/Operational',
  'Microsoft-Exchange-HighAvailability/Operational',
  'Microsoft-Exchange-HighAvailability/Debug',
  'LOGbndSP',
  'MS_Forefront_TMG_WP',
  'DNS',
  'Directory',
  'Windows PowerShell',
  'Replication',
  'File',
  'Operations',
  'Microsoft-Windows-TerminalServices',
  'Microsoft-Windows-GroupPolicy',
  'Directory Service',
  'Microsoft-Windows-Windows Firewall With Advanced Security',
  'Microsoft-Windows-PowerShell',
  'Microsoft-Windows-TaskScheduler',
  'Microsoft-Windows-Sysmon',
  'ALLCHANNEL',
  'Microsoft-Windows-PrintService',
  'Microsoft-Windows-EventForwarder',
  'NetWitness Informer_1000_Informer Web',
  'MSExchange2k13'
];
