export const FETCH_GROUPS = 'USM::FETCH_GROUPS';

// export const FETCH_GROUPS_STARTED = 'USM::FETCH_GROUPS_STARTED';
// export const FETCH_GROUPS_STREAM_INITIALIZED = 'USM::FETCH_GROUPS_STREAM_INITIALIZED';
// export const FETCH_GROUPS_COMPLETED = 'USM::FETCH_GROUPS_STREAM_COMPLETED';
// export const FETCH_GROUPS_ERROR = 'USM::FETCH_GROUPS_ERROR';
// export const FETCH_GROUPS_RETRIEVE_BATCH = 'USM::FETCH_GROUPS_RETRIEVE_BATCH';
// export const FETCH_GROUPS_TOTAL_COUNT = 'USM::FETCH_GROUPS_TOTAL_COUNT';
// export const FETCH_GROUP_DETAILS = 'USM::FETCH_GROUP_DETAILS';


export const GROUPS_TOGGLE_FILTER_PANEL = 'USM::GROUPS_TOGGLE_FILTER_PANEL';
export const GROUPS_UPDATE_FILTERS = 'USM::GROUPS_UPDATE_FILTERS';
export const GROUPS_RESET_FILTERS = 'USM::GROUPS_RESET_FILTERS';
export const GROUPS_TOGGLE_FOCUS = 'USM::GROUPS_TOGGLE_FOCUS';
export const GROUPS_CLEAR_FOCUS = 'USM::GROUPS_CLEAR_FOCUS';
export const GROUPS_TOGGLE_SELECTED = 'USM::GROUPS_TOGGLE_SELECTED';
export const GROUPS_TOGGLE_SELECT_ALL = 'USM::GROUPS_TOGGLE_SELECT_ALL';
export const GROUPS_SORT_BY = 'USM::GROUPS_SORT_BY';


export const INIT_GROUP_FETCH_POLICIES = 'USM::INIT_GROUP_FETCH_POLICIES';
export const NEW_GROUP = 'USM::NEW_GROUP';
export const EDIT_GROUP = 'USM::EDIT_GROUP';
export const SAVE_GROUP = 'USM::SAVE_GROUP';

export const FETCH_POLICY_LIST = 'USM::FETCH_POLICY_LIST';
export const NEW_POLICY = 'USM::NEW_POLICY';
export const EDIT_POLICY = 'USM::EDIT_POLICY';
export const SAVE_POLICY = 'USM::SAVE_POLICY';
export const UPDATE_POLICY_PROPERTY = 'USM::UPDATE_POLICY_PROPERTY';
