
// USM-API-FETCH ITEMS
export const FETCH_GROUPS = 'USM::FETCH_GROUPS';
export const FETCH_POLICIES = 'USM::FETCH_POLICIES';


// USM-GROUPS ITEMS
export const GROUPS_TOGGLE_FILTER_PANEL = 'USM::GROUPS_TOGGLE_FILTER_PANEL';
export const GROUPS_UPDATE_FILTERS = 'USM::GROUPS_UPDATE_FILTERS';
export const GROUPS_RESET_FILTERS = 'USM::GROUPS_RESET_FILTERS';
export const GROUPS_TOGGLE_FOCUS = 'USM::GROUPS_TOGGLE_FOCUS';
export const GROUPS_CLEAR_FOCUS = 'USM::GROUPS_CLEAR_FOCUS';
export const GROUPS_TOGGLE_SELECTED = 'USM::GROUPS_TOGGLE_SELECTED';
export const GROUPS_TOGGLE_SELECT_ALL = 'USM::GROUPS_TOGGLE_SELECT_ALL';
export const GROUPS_SORT_BY = 'USM::GROUPS_SORT_BY';


// USM-GROUP(S) ACTIONS
export const INIT_GROUP_FETCH_POLICIES = 'USM::INIT_GROUP_FETCH_POLICIES';
export const NEW_GROUP = 'USM::NEW_GROUP';
export const EDIT_GROUP = 'USM::EDIT_GROUP';
export const SAVE_GROUP = 'USM::SAVE_GROUP';
export const DELETE_GROUPS = 'USM::DELETE_GROUPS';
export const PUBLISH_GROUPS = 'USM::PUBLISH_GROUPS';


// USM-POLICIES ITEMS
export const POLICIES_TOGGLE_FILTER_PANEL = 'USM::POLICIES_TOGGLE_FILTER_PANEL';
export const POLICIES_UPDATE_FILTERS = 'USM::POLICIES_UPDATE_FILTERS';
export const POLICIES_RESET_FILTERS = 'USM::POLICIES_RESET_FILTERS';
export const POLICIES_TOGGLE_FOCUS = 'USM::POLICIES_TOGGLE_FOCUS';
export const POLICIES_CLEAR_FOCUS = 'USM::POLICIES_CLEAR_FOCUS';
export const POLICIES_TOGGLE_SELECTED = 'USM::POLICIES_TOGGLE_SELECTED';
export const POLICIES_TOGGLE_SELECT_ALL = 'USM::POLICIES_TOGGLE_SELECT_ALL';
export const POLICIES_SORT_BY = 'USM::POLICIES_SORT_BY';


// USM-POLICY(IES) ACTIONS
export const NEW_POLICY = 'USM::NEW_POLICY';
export const EDIT_POLICY = 'USM::EDIT_POLICY';
export const SAVE_POLICY = 'USM::SAVE_POLICY';
export const DELETE_POLICIES = 'USM::DELETE_POLICIES';
export const PUBLISH_POLICIES = 'USM::PUBLISH_POLICIES';
export const UPDATE_POLICY_PROPERTY = 'USM::UPDATE_POLICY_PROPERTY';
export const TOGGLE_SCAN_TYPE = 'USM::TOGGLE_SCAN_TYPE';
export const RESET_SCAN_SCHEDULE_TO_DEFAULTS = 'USM::RESET_SCAN_SCHEDULE_TO_DEFAULTS';
export const ADD_TO_SELECTED_SETTINGS = 'USM::ADD_TO_SELECTED_SETTINGS';
export const REMOVE_FROM_SELECTED_SETTINGS = 'USM::REMOVE_FROM_SELECTED_SETTINGS';

