// Endpoint filters, which are same for hosts, files and certificates

export const GET_FILTER = 'ENDPOINT::GET_FILTER';
export const DELETE_FILTER = 'ENDPOINT::DELETE_FILTER';
export const APPLY_FILTER = 'ENDPOINT::APPLY_FILTER';
export const APPLY_SAVED_FILTER = 'ENDPOINT::APPLY_SAVED_FILTER';
export const SET_SAVED_FILTER = 'ENDPOINT::SET_SAVED_FILTER';
export const SAVE_FILTER = 'ENDPOINT::SAVE_FILTER';
export const RESET_FILTER = 'ENDPOINT::RESET_FILTER';


// Risk Score filters, which are same for Hosts and files.
export const RESET_RISK_SCORE = 'RISK_SCORE::ACTION_TYPES.RESET_RISK_SCORE';
export const RESET_RISK_CONTEXT = 'RISK_SCORE::RESET_RISK_CONTEXT';
export const GET_RISK_SCORE_CONTEXT = 'RISK_SCORE::GET_RISK_SCORE_CONTEXT';

export const SET_SELECTED_ALERT = 'RISK_SCORE::SET_SELECTED_ALERT';
export const ACTIVE_RISK_SEVERITY_TAB = 'RISK_SCORE::ACTIVE_RISK_SEVERITY_TAB';
export const GET_EVENTS = 'INVESTIGATE_FILES::GET_EVENTS';
export const GET_EVENTS_COMPLETED = 'INVESTIGATE_FILES::GET_EVENTS_COMPLETED';
export const GET_EVENTS_ERROR = 'INVESTIGATE_FILES::GET_EVENTS_ERROR';


// export const INITIALIZE_FILE_DETAIL = 'INVESTIGATE_FILES::INITIALIZE_FILE_DETAIL';
export const SET_SELECTED_FILE = 'INVESTIATE_FILES::SET_SELECTED_FILE';


export const EXPANDED_EVENT = 'INVESTIGATE_FILES::EXPANDED_EVENT';


// Investigate preference
export const SET_INVESTIGATE_PREFERENCE = 'ENDPOINT::SET_INVESTIGATE_PREFERENCE';
