export const FETCH_ALL_SPRINGBOARD = 'SPRINGBOARD::FETCH_ALL_SPRINGBOARD';
export const SET_ACTIVE_SPRINGBOARD_ID = 'SPRINGBOARD::SET_ACTIVE_SPRINGBOARD_ID';
export const SET_DEFAULT_ACTIVE_LEADS = 'SPRINGBOARD::SET_DEFAULT_ACTIVE_LEADS';
export const SET_PAGER_POSITION = 'SPRINGBOARD::SET_PAGER_POSITION';