export const META_ARROW_LEFT_KEY = 'PILL::META_ARROW_LEFT_KEY';
export const META_ARROW_RIGHT_KEY = 'PILL::META_ARROW_RIGHT_KEY';
export const META_CLICKED = 'PILL::META_CLICKED';
export const META_ESCAPE_KEY = 'PILL::META_ESCAPE_KEY';
export const META_SELECTED = 'PILL::META_SELECTED';

export const OPERATOR_ARROW_LEFT_KEY = 'PILL::OPERATOR_ARROW_LEFT_KEY';
export const OPERATOR_ARROW_RIGHT_KEY = 'PILL::OPERATOR_ARROW_RIGHT_KEY';
export const OPERATOR_BACKSPACE_KEY = 'PILL::OPERATOR_BACKSPACE_KEY';
export const OPERATOR_CLICKED = 'PILL::OPERATOR_CLICKED';
export const OPERATOR_ESCAPE_KEY = 'PILL::OPERATOR_ESCAPE_KEY';
export const OPERATOR_SELECTED = 'PILL::OPERATOR_SELECTED';

export const VALUE_ARROW_LEFT_KEY = 'PILL::VALUE_ARROW_LEFT_KEY';
export const VALUE_ARROW_RIGHT_KEY = 'PILL::VALUE_ARROW_RIGHT_KEY';
export const VALUE_BACKSPACE_KEY = 'PILL::VALUE_BACKSPACE_KEY';
export const VALUE_CLICKED = 'PILL::VALUE_CLICKED';
export const VALUE_ENTER_KEY = 'PILL::VALUE_ENTER_KEY';
export const VALUE_ESCAPE_KEY = 'PILL::VALUE_ESCAPE_KEY';
export const VALUE_SET = 'PILL::VALUE_SET';

export const DELETE_CLICKED = 'PILL::DELETE_CLICKED';

export const PILL_CANCELLED = 'PILL::CANCELLED';
export const PILL_CREATED = 'PILL::CREATED';
export const PILL_DELETED = 'PILL::DELETED';
export const PILL_EDITED = 'PILL::EDITED';
export const PILL_ENTERED_FOR_APPEND_NEW = 'PILL::ENTERED_FOR_APPEND_NEW';
export const PILL_ENTERED_FOR_EDIT = 'PILL::ENTERED_FOR_EDIT';
export const PILL_ENTERED_FOR_INSERT_NEW = 'PILL::ENTERED_FOR_INSERT_NEW';
export const PILL_OPEN_FOR_EDIT = 'PILL::OPEN_FOR_EDIT';
export const PILL_SELECTED = 'PILL::PILL_SELECTED';
export const PILL_DESELECTED = 'PILL::PILL_DESELECTED';

