export const META_ARROW_LEFT_KEY = 'PILL::META_ARROW_LEFT_KEY';
export const META_ARROW_RIGHT_KEY = 'PILL::META_ARROW_RIGHT_KEY';
export const META_ARROW_RIGHT_KEY_WITH_NO_SELECTION = 'PILL::META_ARROW_RIGHT_KEY_WITH_NO_SELECTION';
export const META_CLICKED = 'PILL::META_CLICKED';
export const META_ENTER_KEY = 'PILL::META_ENTER_KEY';
export const META_ESCAPE_KEY = 'PILL::META_ESCAPE_KEY';
export const META_SELECTED = 'PILL::META_SELECTED';

export const OPERATOR_ARROW_LEFT_KEY = 'PILL::OPERATOR_ARROW_LEFT_KEY';
export const OPERATOR_ARROW_RIGHT_KEY = 'PILL::OPERATOR_ARROW_RIGHT_KEY';
export const OPERATOR_BACKSPACE_KEY = 'PILL::OPERATOR_BACKSPACE_KEY';
export const OPERATOR_CLICKED = 'PILL::OPERATOR_CLICKED';
export const OPERATOR_ESCAPE_KEY = 'PILL::OPERATOR_ESCAPE_KEY';
export const OPERATOR_SELECTED = 'PILL::OPERATOR_SELECTED';

export const VALUE_ARROW_LEFT_KEY = 'PILL::VALUE_ARROW_LEFT_KEY';
export const VALUE_ARROW_RIGHT_KEY = 'PILL::VALUE_ARROW_RIGHT_KEY';
export const VALUE_BACKSPACE_KEY = 'PILL::VALUE_BACKSPACE_KEY';
export const VALUE_CLICKED = 'PILL::VALUE_CLICKED';
export const VALUE_ENTER_KEY = 'PILL::VALUE_ENTER_KEY';
export const VALUE_ESCAPE_KEY = 'PILL::VALUE_ESCAPE_KEY';
export const VALUE_SET = 'PILL::VALUE_SET';

export const DELETE_CLICKED = 'PILL::DELETE_CLICKED';

export const FOCUSED_PILL_DELETE_PRESSED = 'PILL::FOCUSED_PILL_DELETE_PRESSED';
export const FOCUSED_PILL_ENTER_PRESSED = 'PILL::FOCUSED_PILL_ENTER_PRESSED';
export const FOCUSED_PILL_LEFT_ARROW_PRESSED = 'PILL::FOCUSED_PILL_LEFT_ARROW_PRESSED';
export const FOCUSED_PILL_RIGHT_ARROW_PRESSED = 'PILL::FOCUSED_PILL_RIGHT_ARROW_PRESSED';
export const FOCUSED_PILL_SHIFT_DOWN_RIGHT_ARROW_PRESSED = 'PILL::FOCUSED_PILL_SHIFT_DOWN_RIGHT_ARROW_PRESSED';
export const FOCUSED_PILL_SHIFT_UP_LEFT_ARROW_PRESSED = 'PILL::FOCUSED_PILL_SHIFT_UP_LEFT_ARROW_PRESSED';

export const DELETE_PRESSED_ON_FOCUSED_PILL = 'PILL::DELETE_PRESSED_ON_FOCUSED_PILL';
export const ENTER_PRESSED_ON_FOCUSED_PILL = 'PILL::ENTER_PRESSED_ON_FOCUSED_PILL';
export const SELECT_ALL_PILLS_TO_RIGHT = 'PILL::SELECT_ALL_PILLS_TO_RIGHT';
export const SELECT_ALL_PILLS_TO_LEFT = 'PILL::SELECT_ALL_PILLS_TO_LEFT';

export const PILL_ADD_CANCELLED = 'PILL::ADD_CANCELLED';
export const PILL_CREATED = 'PILL::CREATED';
export const PILL_DELETED = 'PILL::DELETED';
export const PILL_EDIT_CANCELLED = 'PILL::EDIT_CANCELLED';
export const PILL_EDITED = 'PILL::EDITED';
export const PILL_ENTERED_FOR_APPEND_NEW = 'PILL::ENTERED_FOR_APPEND_NEW';
export const PILL_ENTERED_FOR_INSERT_NEW = 'PILL::ENTERED_FOR_INSERT_NEW';
export const PILL_FOCUS_EXIT_TO_RIGHT = 'PILL::FOCUS_EXIT_TO_RIGHT';
export const PILL_FOCUS_EXIT_TO_LEFT = 'PILL::FOCUS_EXIT_TO_LEFT';
export const PILL_INTENT_TO_QUERY = 'PILL::INTENT_TO_QUERY';
export const PILL_OPEN_FOR_EDIT = 'PILL::OPEN_FOR_EDIT';
export const PILL_SELECTED = 'PILL::SELECTED';
export const PILL_TRIGGER_EXIT_FOCUS_TO_LEFT = 'PILL::TRIGGER_EXIT_FOCUS_TO_LEFT';
export const PILL_TRIGGER_EXIT_FOCUS_TO_RIGHT = 'PILL::TRIGGER_EXIT_FOCUS_TO_RIGHT';
export const PILL_DESELECTED = 'PILL::DESELECTED';

export const CREATE_FREE_FORM_PILL = 'PILL::CREATE_FREE_FORM_PILL';
export const CREATE_TEXT_PILL = 'PILL::CREATE_TEXT_PILL';

export const AFTER_OPTIONS_SELECTED = 'EPS_AFTER_OPTION::SELECTED';
export const AFTER_OPTIONS_HIGHLIGHT = 'EPS_AFTER_OPTION::HIGHLIGHT';
export const AFTER_OPTIONS_REMOVE_HIGHLIGHT = 'EPS_AFTER_OPTION::REMOVE_HIGHLIGHT';
export const AFTER_OPTIONS_TAB_CLICKED = 'AFTER_OPTION_TAB::CLICKED';
export const AFTER_OPTIONS_TAB_TOGGLED = 'AFTER_OPTION_TAB::TOGGLED';

export const RECENT_QUERIES_TEXT_TYPED = 'RECENT_QUERIES::TEXT_TYPED';
export const RECENT_QUERIES_SUGGESTIONS_FOR_TEXT = 'RECENT_QUERIES::SUGGESTIONS_FOR_TEXT';
export const RECENT_QUERIES_ESCAPE_KEY = 'RECENT_QUERIES::ESCAPE_KEY';