export const DEBUG = 'DEBUG';

// PILL EVENTS
export const META_SELECTED = 'PILL::META_SELECTED';
export const OPERATOR_SELECTED = 'PILL::OPERATOR_SELECTED';
export const PILL_INITIALIZED = 'PILL::INITIALIZED';
export const VALUE_ENTER_KEY = 'PILL::VALUE_ENTER_KEY';
export const VALUE_ESCAPE_KEY = 'PILL::VALUE_ESCAPE_KEY';
export const VALUE_BACKSPACE_KEY = 'PILL::VALUE_BACKSPACE_KEY';
export const VALUE_ARROW_LEFT_KEY = 'PILL::VALUE_ARROW_LEFT_KEY';
export const VALUE_ARROW_RIGHT_KEY = 'PILL::VALUE_ARROW_RIGHT_KEY';
export const VALUE_SET = 'PILL::VALUE_SET';