// Data Retrieval Related Action Types
export const FETCH_ALL_FILTERS = 'INVESTIGATE_HOSTS::FETCH_ALL_FILTERS';
export const FETCH_ALL_MACHINES = 'INVESTIGATE_HOSTS::FETCH_ALL_MACHINES';
export const FETCH_NEXT_MACHINES = 'INVESTIGATE_HOSTS::FETCH_NEXT_MACHINES';
export const FETCH_ALL_SCHEMAS = 'INVESTIGATE_HOSTS::FETCH_ALL_SCHEMAS';
export const CREATE_CUSTOM_SEARCH = 'INVESTIGATE_HOSTS::CREATE_CUSTOM_SEARCH';
export const FETCH_DOWNLOAD_JOB_ID = 'INVESTIGATE_HOSTS::FETCH_DOWNLOAD_JOB_ID';
export const DELETE_HOSTS = 'INVESTIGATE_HOSTS::DELETE_HOSTS';

export const FETCH_AGENT_STATUS_STREAM_INITIALIZED = 'INVESTIGATE_HOSTS::FETCH_AGENT_STATUS_STREAM_INITIALIZED';
export const FETCH_AGENT_STATUS = 'INVESTIGATE_HOSTS::FETCH_AGENT_STATUS';

export const FETCH_ALL_SNAP_SHOTS = 'INVESTIGATE_HOSTS::FETCH_ALL_SNAP_SHOTS';
export const FETCH_HOST_DETAILS = 'INVESTIGATE_HOSTS::FETCH_HOST_DETAILS';
export const FETCH_DOWNLOAD_FILECONTEXT_JOB_ID = 'INVESTIGATE_HOSTS::FETCH_DOWNLOAD_FILECONTEXT_JOB_ID';

// UI Action Types
export const TOGGLE_MACHINE_SELECTED = 'INVESTIGATE_HOSTS::TOGGLE_MACHINE_SELECTED';
export const EXECUTE_QUERY = 'INVESTIGATE_HOSTS::EXECUTE_QUERY';
export const SET_SELECTED_HOST = 'INVESTIGATE_HOSTS::SET_SELECTED_HOST';
export const TOGGLE_ICON_VISIBILITY = 'INVESTIGATE_HOSTS::TOGGLE_ICON_VISIBILITY';

export const CHANGE_DETAIL_TAB = 'INVESTIGATE_HOSTS::CHANGE_DETAIL_TAB';
export const CHANGE_AUTORUNS_TAB = 'INVESTIGATE_HOSTS::CHANGE_AUTORUNS_TAB';
export const RESET_HOST_DETAILS = 'INVESTIGATE_HOSTS::RESET_HOST_DETAILS';
export const RESET_INPUT_DATA = 'INVESTIGATE_HOSTS::RESET_INPUT_DATA';
export const TOGGLE_OVERVIEW_PANEL = 'INVESTIGATE_HOSTS::TOGGLE_OVERVIEW_PANEL';
export const TOGGLE_SHOW_PROPERTY_WITH_VALUES = 'INVESTIGATE_HOSTS::TOGGLE_SHOW_PROPERTY_WITH_VALUES';
export const RESET_HOST_DOWNLOAD_LINK = 'INVESTIGATE_HOSTS::RESET_HOST_DOWNLOAD_LINK';

// Filter
export const TOGGLE_CUSTOM_FILTER = 'INVESTIGATE_HOSTS::TOGGLE_CUSTOM_FILTER';
export const REMOVE_HOST_FILTER = 'INVESTIGATE_HOSTS::REMOVE_HOST_FILTER';
export const SET_ACTIVE_FILTER = 'INVESTIGATE_HOSTS::SET_ACTIVE_FILTER';
export const ADD_SYSTEM_FILTER = 'INVESTIGATE_HOSTS::ADD_SYSTEM_FILTER';
export const ADD_HOST_FILTER = 'INVESTIGATE_HOSTS::ADD_HOST_FILTER';
export const RESET_HOST_FILTERS = 'INVESTIGATE_HOSTS::RESET_HOST_FILTERS';
export const UPDATE_HOST_FILTER = 'INVESTIGATE_HOSTS::UPDATE_HOST_FILTER';
export const UPDATE_HOST_DATETIME_FILTER = 'INVESTIGATE_HOSTS::UPDATE_HOST_DATETIME_FILTER';
export const UPDATE_FILTER_LIST = 'INVESTIGATE_HOSTS::UPDATE_FILTER_LIST';

// Process
export const GET_PROCESS_LIST = 'INVESTIGATE_HOSTS::GET_PROCESS_LIST';
export const GET_PROCESS_TREE = 'INVESTIGATE_HOSTS::GET_PROCESS_TREE';
export const TOGGLE_PROCESS_VIEW = 'INVESTIGATE_HOSTS::TOGGLE_PROCESS_VIEW';
export const SET_SORT_BY = 'INVESTIGATE_HOSTS::SET_SORT_BY';
export const RESET_PROCESS_LIST = 'INVESTIGATE_HOSTS::RESET_PROCESS_LIST';
export const GET_PROCESS = 'INVESTIGATE_HOSTS::GET_PROCESS';
export const GET_PROCESS_FILE_CONTEXT = 'INVESTIGATE_HOSTS::GET_PROCESS_FILE_CONTEXT';

export const GET_LIBRARY_PROCESS_INFO = 'INVESTIGATE_HOSTS::GET_LIBRARY_PROCESS_INFO';

// DATA
export const INITIALIZE_DATA = 'INVESTIGATE_HOSTS::INITIALIZE_DATA';

export const SET_SCAN_TIME = 'INVESTIGATE_HOSTS::SET_SCAN_TIME';
export const SET_ANIMATION = 'INVESTIGATE_HOSTS::SET_ANIMATION';

// Files
export const GET_HOST_FILES = 'INVESTIGATE_HOSTS::GET_HOST_FILES';
export const RESET_HOST_FILES = 'INVESTIGATE_HOSTS::RESET_HOST_FILES';
export const SET_HOST_FILES_SORT_BY = 'INVESTIGATE_HOSTS::SET_HOST_FILES_SORT_BY';
export const INCREMENT_PAGE_NUMBER = 'INVESTIGATE_HOSTS::INCREMENT_PAGE_NUMBER';
export const SET_SELECTED_FILE = 'INVESTIGATE_HOSTS::SET_SELECTED_FILE';

// Explore
export const START_FILE_SEARCH = 'INVESTIGATE_HOSTS::START_FILE_SEARCH';
export const SELECTED_TAB_DATA = 'INVESTIGATE_HOSTS::SELECTED_TAB_DATA';
export const FILE_SEARCH_PAGE = 'INVESTIGATE_HOSTS::FILE_SEARCH_PAGE';
export const FILE_SEARCH_END = 'INVESTIGATE_HOSTS::FILE_SEARCH_END';


// FileContext
export const FETCH_FILE_CONTEXT_AUTORUNS = 'INVESTIGATE_HOSTS::FETCH_FILE_CONTEXT_AUTORUNS';
export const FETCH_FILE_CONTEXT_SERVICES = 'INVESTIGATE_HOSTS::FETCH_FILE_CONTEXT_SERVICES';
export const FETCH_FILE_CONTEXT_TASKS = 'INVESTIGATE_HOSTS::FETCH_FILE_CONTEXT_TASKS';
export const SET_AUTORUN_SELECTED_ROW = 'INVESTIGATE_HOSTS::SET_AUTORUN_SELECTED_ROW';

export const FETCH_FILE_CONTEXT_DRIVERS = 'INVESTIGATE_HOSTS::FETCH_FILE_CONTEXT_DRIVERS';
export const SET_DRIVERS_SELECTED_ROW = 'INVESTIGATE_HOSTS::SET_DRIVERS_SELECTED_ROW';

export const FETCH_FILE_CONTEXT_DLLS = 'INVESTIGATE_HOSTS::FETCH_FILE_CONTEXT_DLLS';
export const SET_DLLS_SELECTED_ROW = 'INVESTIGATE_HOSTS::SET_DLLS_SELECTED_ROW';

export const UPDATE_COLUMN_VISIBILITY = 'INVESTIGATE_HOSTS::UPDATE_COLUMN_VISIBILITY';

export const SET_HOST_COLUMN_SORT = 'INVESTIGATE_HOSTS::SET_HOST_COLUMN_SORT';
export const USER_LEFT_HOST_LIST_PAGE = 'INVESTIGATE_HOSTS::USER_LEFT_HOST_LIST_PAGE';
export const SET_APPLIED_HOST_FILTER = 'INVESTIGATE_HOSTS::SET_APPLIED_HOST_FILTER';
export const TOGGLE_EXPLORE_SEARCH_RESULTS = 'INVESTIGATE_HOSTS::TOGGLE_EXPLORE_SEARCH_RESULTS';
export const RESET_EXPLORED_RESULTS = 'INVESTIGATE_HOSTS::RESET_EXPLORED_RESULTS';

export const SELECT_ALL_HOSTS = 'INVESTIGATE_HOSTS::SELECT_ALL_HOSTS';
export const DESELECT_ALL_HOSTS = 'INVESTIGATE_HOSTS::DESELECT_ALL_HOSTS';
export const TOGGLE_INITIATE_SCAN_MODAL = 'INVESTIGATE_HOSTS::TOGGLE_INITIATE_SCAN_MODAL';
export const TOGGLE_CANCEL_SCAN_MODAL = 'INVESTIGATE_HOSTS::TOGGLE_CANCEL_SCAN_MODAL';
export const TOGGLE_DELETE_HOSTS_MODAL = 'INVESTIGATE_HOSTS::TOGGLE_DELETE_HOSTS_MODAL';

export const DELETE_SAVED_SEARCH = 'INVESTIGATE_HOSTS::DELETE_SAVED_SEARCH';

export const GET_PREFERENCES = 'INVESTIGATE_HOSTS::GET_PREFERENCES';

