export const REHYDRATE = 'persist/REHYDRATE';

export const INITIALIZE_INVESTIGATE = 'INVESTIGATE_EVENTS::INITIALIZE_INVESTIGATE';
export const SET_PREFERENCES = 'INVESTIGATE_EVENTS::SET_PREFERENCES';
export const COLUMNS_RETRIEVE = 'INVESTIGATE_EVENTS::COLUMNS_RETRIEVE';

// Services action types
export const SERVICE_SELECTED = 'INVESTIGATE_EVENTS::SERVICE_SELECTED';
export const SERVICES_RETRIEVE = 'INVESTIGATE_EVENTS::SERVICES_RETRIEVE';

// Session action typess
export const SESSION_SELECTED = 'INVESTIGATE_EVENTS::SESSION_SELECTED';

// Dictionary action types
export const ALIASES_RETRIEVE = 'INVESTIGATE_EVENTS::ALIASES_RETRIEVE';
export const ALIASES_GET_FROM_CACHE = 'INVESTIGATE_EVENTS::ALIASES_GET_FROM_CACHE';
export const LANGUAGE_RETRIEVE = 'INVESTIGATE_EVENTS::LANGUAGE_RETRIEVE';
export const LANGUAGE_GET_FROM_CACHE = 'INVESTIGATE_EVENTS::LANGUAGE_GET_FROM_CACHE';
// Dictionary helper types for testing
export const SET_ALIASES = 'INVESTIGATE_EVENTS::SET_ALIASES';
export const SET_LANGUAGE = 'INVESTIGATE_EVENTS::SET_LANGUAGE';

// Summary action types
export const SUMMARY_RETRIEVE = 'INVESTIGATE_EVENTS::SUMMARY_RETRIEVE';
export const SUMMARY_UPDATE = 'INVESTIGATE_EVENTS::SUMMARY_UPDATE';

// URL query param action types
export const SET_META_PANEL_SIZE = 'INVESTIGATE_EVENTS::SET_META_PANEL_SIZE';
export const SET_RECON_PANEL_SIZE = 'INVESTIGATE_EVENTS::SET_RECON_PANEL_SIZE';

// Query action types
export const RESET_QUERYNODE = 'INVESTIGATE_EVENTS::RESET_QUERYNODE';
export const SET_QUERY_TIME_RANGE = 'INVESTIGATE_EVENTS::SET_QUERY_TIME_RANGE';
export const SET_QUERY_VIEW = 'INVESTIGATE_EVENTS::SET_QUERY_VIEW';
export const SET_FREE_FORM_TEXT = 'INVESTIGATE_EVENTS::SET_FREE_FORM_TEXT';

// View state action types
export const SET_RECON_VIEWABLE = 'INVESTIGATE_EVENTS::SET_RECON_VIEWABLE';

// Event action types
export const INIT_EVENTS_STREAMING = 'INVESTIGATE_EVENTS::INIT_EVENTS_STREAMING';
export const GET_EVENT_COUNT = 'INVESTIGATE_EVENTS::GET_EVENT_COUNT';
export const GET_EVENT_TIMELINE = 'INVESTIGATE_EVENTS::GET_EVENT_TIMELINE';
export const SET_EVENTS_PAGE = 'INVESTIGATE_EVENTS::SET_EVENTS_PAGE';
export const SET_EVENTS_PAGE_ERROR = 'INVESTIGATE_EVENTS::SET_EVENTS_PAGE_ERROR';
export const SET_EVENTS_PAGE_STATUS = 'INVESTIGATE_EVENTS::SET_EVENTS_PAGE_STATUS';
export const SET_ANCHOR = 'INVESTIGATE_EVENTS::SET_ANCHOR';
export const SET_GOAL = 'INVESTIGATE_EVENTS::SET_GOAL';
export const GET_LOG = 'INVESTIGATE::GET_LOG';
export const SET_LOG = 'INVESTIGATE::SET_LOG';
export const SET_LOG_STATUS = 'INVESTIGATE::SET_LOG_STATUS';
export const SET_SELECTED_COLUMN_GROUP = 'INVESTIGATE::SET_SELECTED_COLUMN_GROUP';

// Next Gen Action types
export const INITIALIZE_QUERYING = 'INVESTIGATE_EVENTS::INITIALIZE_QUERYING';
export const ADD_GUIDED_PILL = 'INVESTIGATE_EVENTS::ADD_GUIDED_PILL';
export const DELETE_GUIDED_PILLS = 'INVESTIGATE_EVENTS::DELETE_GUIDED_PILLS';
export const DESELECT_GUIDED_PILLS = 'INVESTIGATE_EVENTS::DESELECT_GUIDED_PILLS';
export const EDIT_GUIDED_PILL = 'INVESTIGATE_EVENTS::EDIT_GUIDED_PILL';
export const OPEN_GUIDED_PILL_FOR_EDIT = 'INVESTIGATE_EVENTS::OPEN_GUIDED_PILL_FOR_EDIT';
export const REPLACE_ALL_GUIDED_PILLS = 'INVESTIGATE_EVENTS::REPLACE_ALL_GUIDED_PILLS';
export const RESET_GUIDED_PILL = 'INVESTIGATE_EVENTS::RESET_GUIDED_PILL';
export const SELECT_GUIDED_PILLS = 'INVESTIGATE_EVENTS::SELECT_GUIDED_PILLS';
export const UPDATE_FREE_FORM_TEXT = 'INVESTIGATE_EVENTS::UPDATE_FREE_FORM_TEXT';
export const VALIDATE_GUIDED_PILL = 'INVESTIGATE_EVENTS::VALIDATE_GUIDED_PILL';

export const RETRIEVE_QUERY_PARAMS_FOR_HASHES = 'INVESTIGATE_EVENTS::RETRIEVE_QUERY_PARAMS_FOR_HASHES';
export const RETRIEVE_HASH_FOR_QUERY_PARAMS = 'INVESTIGATE_EVENTS::RETRIEVE_HASH_FOR_QUERY_PARAMS';