export const GET_CERTIFICATES = 'ENDPOINT::GET_CERTIFICATES';
export const SAVE_CERTIFICATE_STATUS = 'ENDPOINT::SAVE_CERTIFICATE_STATUS';
export const GET_CERTIFICATE_STATUS = 'ENDPOINT::GET_CERTIFICATE_STATUS';
export const INCREMENT_PAGE_NUMBER = 'ENDPOINT::INCREMENT_PAGE_NUMBER';
export const TOGGLE_SELECTED_CERTIFICATE = 'ENDPOINT::TOGGLE_SELECTED_CERTIFICATE';
export const TOGGLE_ALL_CERTIFICATE_SELECTION = 'ENDPOINT::TOGGLE_ALL_CERTIFICATE_SELECTION';
