export const LEFT_PAREN = 'LEFT_PAREN';
export const RIGHT_PAREN = 'RIGHT_PAREN';
export const AND = 'AND';
export const OR = 'OR';

export const META = 'META';
export const OPERATOR_EQ = 'OPERATOR_EQ';
export const OPERATOR_NOT_EQ = 'OPERATOR_NOT_EQ';
export const OPERATOR_LT = 'OPERATOR_LT';
export const OPERATOR_LTE = 'OPERATOR_LTE';
export const OPERATOR_GT = 'OPERATOR_GT';
export const OPERATOR_GTE = 'OPERATOR_GTE';
export const OPERATOR_EXISTS = 'OPERATOR_EXISTS';
export const OPERATOR_NOT_EXISTS = 'OPERATOR_NOT_EXISTS';
export const OPERATOR_BEGINS = 'OPERATOR_BEGINS';
export const OPERATOR_ENDS = 'OPERATOR_ENDS';
export const OPERATOR_CONTAINS = 'OPERATOR_CONTAINS';
export const OPERATOR_REGEX = 'OPERATOR_REGEX';
export const OPERATOR_LENGTH = 'OPERATOR_LENGTH';
export const NUMBER = 'NUMBER';
export const IPV4_ADDRESS = 'IPV4_ADDRESS';
export const IPV6_ADDRESS = 'IPV6_ADDRESS';
export const MAC_ADDRESS = 'MAC_ADDRESS';
export const STRING = 'STRING';
export const TEXT_FILTER = 'TEXT_FILTER';

export const OPERATOR_TYPES = [
  OPERATOR_EQ,
  OPERATOR_NOT_EQ,
  OPERATOR_LT,
  OPERATOR_LTE,
  OPERATOR_GT,
  OPERATOR_GTE,
  OPERATOR_EXISTS,
  OPERATOR_NOT_EXISTS,
  OPERATOR_BEGINS,
  OPERATOR_ENDS,
  OPERATOR_CONTAINS,
  OPERATOR_REGEX,
  OPERATOR_LENGTH
];
