export const AFTER_OPTION_FREE_FORM_LABEL = 'Free-Form Filter';
export const AFTER_OPTION_TEXT_LABEL = 'Text Filter';
export const AFTER_OPTION_TEXT_DISABLED_LABEL = 'Text Filter is unavailable. Only one is permitted.';
export const AFTER_OPTION_QUERY_LABEL = 'Query Filter';
export const AFTER_OPTION_TAB_META = 'meta';
export const AFTER_OPTION_TAB_RECENT_QUERIES = 'recent queries';
export const COMPLEX_OPERATORS = ['!', '&&', '||', '(', ')', ',', '-', 'AND', 'NOT', 'OR', 'length', 'regex'];
export const COMPLEX_FILTER = 'complex';
export const OPERATORS = ['!exists', 'exists', 'contains', 'begins', 'ends', '<=', '>=', '!=', '='];
export const QUERY_FILTER = 'query';
export const SEARCH_TERM_MARKER = '~';
export const TEXT_FILTER = 'text';