export const UPDATE_PREFERENCES_LOCALE = 'GLOBAL::PREFERENCES::UPDATE_LOCALE';
export const ADD_PREFERENCES_LOCALES = 'GLOBAL::PREFERENCES::ADD_LOCALES';
export const UPDATE_PREFERENCES_THEME = 'GLOBAL::PREFERENCES::UPDATE_THEME';
export const REHYDRATE = 'persist/REHYDRATE';
