export const GET_INFO = 'PACKAGER::GET_INFO';
export const SAVE_INFO = 'PACKAGER::SAVE_INFO';
export const RESET_FORM = 'PACKAGER::RESET_FORM';

export const DOWNLOAD_PACKAGE = 'PACKAGER::DOWNLOAD_PACKAGE';
export const RETRIEVE_FAILURE = 'PACKAGER::RETRIEVE_FAILURE';
export const UPDATE_FIELDS = 'PACKAGER::UPDATE_FIELDS';
export const SET_SELECTED_SERVER_IP = 'PACKAGER::SET_SELECTED_SERVER_IP';
export const GET_ENDPOINT_SERVERS = 'PACKAGER::GET_ENDPOINT_SERVERS';
