export const GET_INFO = 'PACKAGER::GET_INFO';
export const SAVE_INFO = 'PACKAGER::SAVE_INFO';
export const GET_DEVICES = 'PACKAGER::GET_DEVICES';
export const RESET_FORM = 'PACKAGER::RESET_FORM';

export const DOWNLOAD_PACKAGE = 'PACKAGER::DOWNLOAD_PACKAGE';
export const RETRIEVE_FAILURE = 'PACKAGER::RETRIEVE_FAILURE';
export const UPDATE_FIELDS = 'PACKAGER::UPDATE_FIELDS';