// context related ACTION_TYPES
export const INITIALIZE_CONTEXT_PANEL = 'CONTEXT::INITIALIZE_CONTEXT_PANEL';
export const GET_LOOKUP_DATA = 'CONTEXT::GET_LOOKUP_DATA';
export const CONTEXT_ERROR = 'CONTEXT::CONTEXT_ERROR';
export const RESTORE_DEFAULT = 'CONTEXT::RESTORE_DEFAULT';
export const GET_CONTEXT_ENTITIES_METAS = 'CONTEXT::GET_CONTEXT_ENTITIES_METAS';
export const UPDATE_PANEL_CLICKED = 'CONTEXT::UPDATE_PANEL_CLICKED';

// tabs related ACTION_TYPES
export const UPDATE_ACTIVE_TAB = 'CONTEXT::UPDATE_ACTIVE_TAB';
export const GET_ALL_DATA_SOURCES = 'CONTEXT::GET_ALL_DATA_SOURCES';

// hover related ACTION_TYPES
export const GET_SUMMARY_DATA = 'CONTEXT:GET_SUMMARY_DATA';

// list related ACTION_TYPES
export const INITIALIZE_ADD_TO_LIST_PARAM = 'CONTEXT::INITIALIZE_ADD_TO_LIST_PARAM';
export const SET_ALL_LIST = 'CONTEXT::SET_ALL_LIST';
export const CREATE_LIST = 'CONTEXT::CREATE_LIST';
export const RESET_ERROR = 'CONTEXT::RESET_ERROR';
export const LIST_ERROR = 'CONTEXT::LIST_ERROR';
export const TOGGLE_LIST_VIEW = 'CONTEXT::TOGGLE_LIST_VIEW';
