export default [{
  'id': '58be7d121969557cbbdbfc57',
  'name': '58be7d121969557cbbdbfc55_Incidents_datasource',
  'enabled': true,
  'description': null,
  'type': 'Archer',
  'dataSourceGroup': 'Archer',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 13,
  'contentLastModifiedTime': 1488906967222
}, {
  'id': '58be7d121969557cbbdbfc57',
  'name': '58be7d121969557cbbdbfc55_Incidents_datasource',
  'enabled': true,
  'description': null,
  'type': 'Incidents',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 13,
  'contentLastModifiedTime': 1488906967222,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'alert.events.source.device.ip_address',
      'remoteFieldName': 'alert.events.source.device.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Source Device IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.ip_address',
      'remoteFieldName': 'alert.events.destination.device.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination Device IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.device.ip_address',
      'remoteFieldName': 'alert.events.detector.device.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector Device IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.ip_address',
      'remoteFieldName': 'alert.events.detector.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.ip_address',
      'remoteFieldName': 'alert.events.source.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Source IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.ip_address',
      'remoteFieldName': 'alert.events.destination.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.user',
      'remoteFieldName': 'alert.user',
      'dataType': null,
      'fieldDescription': 'Alert User',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.user',
      'remoteFieldName': 'alert.events.user',
      'dataType': null,
      'fieldDescription': 'Alert User',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.user.ad_username',
      'remoteFieldName': 'alert.events.source.user.ad_username',
      'dataType': null,
      'fieldDescription': 'Alert Source AD User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.user.ad_username',
      'remoteFieldName': 'alert.events.destination.user.ad_username',
      'dataType': null,
      'fieldDescription': 'Alert Destination AD User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.user.username',
      'remoteFieldName': 'alert.events.source.user.username',
      'dataType': null,
      'fieldDescription': 'Alert Source User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.user.username',
      'remoteFieldName': 'alert.events.destination.user.username',
      'dataType': null,
      'fieldDescription': 'Alert Destination User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.dns_hostname',
      'remoteFieldName': 'alert.events.source.dns_hostname',
      'dataType': null,
      'fieldDescription': 'Alert Source Host Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.dns_hostname',
      'remoteFieldName': 'alert.events.destination.dns_hostname',
      'dataType': null,
      'fieldDescription': 'Alert Destination Host Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.dns_hostname',
      'remoteFieldName': 'alert.events.detector.dns_hostname',
      'dataType': null,
      'fieldDescription': 'Alert Detector Host Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.device.netbios_name',
      'remoteFieldName': 'alert.events.source.device.netbios_name',
      'dataType': null,
      'fieldDescription': 'Alert Source Device NetBIOS Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.netbios_name',
      'remoteFieldName': 'alert.events.destination.device.netbios_name',
      'dataType': null,
      'fieldDescription': 'Alert Destination Device NetBIOS Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.domain',
      'remoteFieldName': 'alert.events.domain',
      'dataType': null,
      'fieldDescription': 'Alert Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.dns_domain',
      'remoteFieldName': 'alert.events.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.dns_domain',
      'remoteFieldName': 'alert.events.source.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert Source DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.dns_domain',
      'remoteFieldName': 'alert.events.destination.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert Destination DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.dns_domain',
      'remoteFieldName': 'alert.events.detector.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert Detector DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.user.ad_domain',
      'remoteFieldName': 'alert.events.source.user.ad_domain',
      'dataType': null,
      'fieldDescription': 'Alert Source AD Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.user.ad_domain',
      'remoteFieldName': 'alert.events.destination.user.ad_domain',
      'dataType': null,
      'fieldDescription': 'Alert Destination AD Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.device.geolocation.domain',
      'remoteFieldName': 'alert.events.source.device.geolocation.domain',
      'dataType': null,
      'fieldDescription': 'Alert Source Geolocation Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.geolocation.domain',
      'remoteFieldName': 'alert.events.destination.device.geolocation.domain',
      'dataType': null,
      'fieldDescription': 'Alert Destination Geolocation Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.mac_address',
      'remoteFieldName': 'alert.events.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.device.mac_address',
      'remoteFieldName': 'alert.events.source.device.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Source MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.mac_address',
      'remoteFieldName': 'alert.events.destination.device.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.device.mac_address',
      'remoteFieldName': 'alert.events.detector.device.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector Device MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.mac_address',
      'remoteFieldName': 'alert.events.detector.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.mac_address',
      'remoteFieldName': 'alert.events.source.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Source MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.mac_address',
      'remoteFieldName': 'alert.events.destination.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.file',
      'remoteFieldName': 'alert.events.file',
      'dataType': null,
      'fieldDescription': 'Alert File Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.data.filename',
      'remoteFieldName': 'alert.events.data.filename',
      'dataType': null,
      'fieldDescription': 'Alert Data File Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.data.hash',
      'remoteFieldName': 'alert.events.data.hash',
      'dataType': null,
      'fieldDescription': 'Alert Data Hash',
      'primaryKey': false
    }, {
      'fieldName': 'entityValue',
      'remoteFieldName': 'entityValue',
      'dataType': null,
      'fieldDescription': 'Entity Value',
      'primaryKey': false
    }, {
      'fieldName': 'id',
      'remoteFieldName': 'id',
      'dataType': null,
      'fieldDescription': 'Incident Id',
      'primaryKey': false
    }, {
      'fieldName': 'name',
      'remoteFieldName': 'name',
      'dataType': null,
      'fieldDescription': 'Incident Name',
      'primaryKey': false
    }, {
      'fieldName': 'created',
      'remoteFieldName': 'created',
      'dataType': null,
      'fieldDescription': 'Incident Created Time',
      'primaryKey': false
    }, {
      'fieldName': 'alertCount',
      'remoteFieldName': 'alertCount',
      'dataType': null,
      'fieldDescription': 'Incident Alerts Count',
      'primaryKey': false
    }, {
      'fieldName': 'status',
      'remoteFieldName': 'status',
      'dataType': null,
      'fieldDescription': 'Incident Status',
      'primaryKey': false
    }, {
      'fieldName': 'assignee.name',
      'remoteFieldName': 'assignee.name',
      'dataType': null,
      'fieldDescription': 'Incident Assignee Name',
      'primaryKey': false
    }, {
      'fieldName': 'priority',
      'remoteFieldName': 'priority',
      'dataType': null,
      'fieldDescription': 'Incident Priority',
      'primaryKey': false
    }, {
      'fieldName': 'averageAlertRiskScore',
      'remoteFieldName': 'averageAlertRiskScore',
      'dataType': null,
      'fieldDescription': 'Incident Average Alert Risk Score',
      'primaryKey': false
    }, {
      'fieldName': 'alert.timestamp',
      'remoteFieldName': 'alert.timestamp',
      'dataType': null,
      'fieldDescription': 'Alert Timestamp',
      'primaryKey': false
    }, {
      'fieldName': 'incidentId',
      'remoteFieldName': 'incidentId',
      'dataType': null,
      'fieldDescription': 'Alert Incident Id',
      'primaryKey': false
    }, {
      'fieldName': 'timeStamp',
      'remoteFieldName': 'timeStamp',
      'dataType': null,
      'fieldDescription': 'Prefetch Data Timestamp',
      'primaryKey': false
    }],
    'entityMapping': {
      'IP': ['alert.events.source.device.ip_address', 'alert.events.destination.device.ip_address', 'alert.events.detector.device.ip_address', 'alert.events.detector.ip_address', 'alert.events.source.ip_address', 'alert.events.destination.ip_address', 'entityValue'],
      'USER': ['alert.user', 'alert.events.user', 'alert.events.source.user.ad_username', 'alert.events.destination.user.ad_username', 'alert.events.source.user.username', 'alert.events.destination.user.username', 'entityValue'],
      'HOST': ['alert.events.source.dns_hostname', 'alert.events.destination.dns_hostname', 'alert.events.detector.dns_hostname', 'alert.events.source.device.netbios_name', 'alert.events.destination.device.netbios_name', 'entityValue'],
      'DOMAIN': ['alert.events.domain', 'alert.events.dns_domain', 'alert.events.source.dns_domain', 'alert.events.destination.dns_domain', 'alert.events.detector.dns_domain', 'alert.events.source.user.ad_domain', 'alert.events.destination.user.ad_domain', 'alert.events.source.device.geolocation.domain', 'alert.events.destination.device.geolocation.domain', 'entityValue'],
      'MAC_ADDRESS': ['alert.events.mac_address', 'alert.events.source.device.mac_address', 'alert.events.destination.device.mac_address', 'alert.events.detector.device.mac_address', 'alert.events.detector.mac_address', 'alert.events.source.mac_address', 'alert.events.destination.mac_address', 'entityValue'],
      'FILE_NAME': ['alert.events.file', 'alert.events.data.filename', 'entityValue'],
      'FILE_HASH': ['alert.events.data.hash', 'entityValue']
    }
  },
  'indexDefinitions': [{
    'indexType': 'TTL',
    'fieldsInIndex': ['timeStamp'],
    'expireAfterSeconds': 604800
  }],
  'dataSourceGroup': 'Incidents',
  'dataSourceConnectionId': '58be7d121969557cbbdbfc55',
  'dataSourceDisplayName': '58be7d121969557cbbdbfc55_Incidents_datasource',
  'tags': [],
  'queryResponseCachePolicy': {
    'enabled': true,
    'maxSizeOfEntryAllowed': '2048 B',
    'maxSecondsInCache': '1800 SECONDS',
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'dataSourceEntriesCachePolicy': {
    'cacheEnabled': true,
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'advancedParameters': {
    'batchAdapterJobParams[0].jobId': 'entityLookup',
    'batchAdapterJobParams[0].schedule': null,
    'batchAdapterJobParams[0].writePolicy': null,
    'batchAdapterJobParams[0].responseMeta.limit': 100,
    'batchAdapterJobParams[0].responseMeta.pageSize': 0,
    'batchAdapterJobParams[0].responseMeta.uniqueId': null,
    'batchAdapterJobParams[0].responseMeta.responseAlias[0]': 'id',
    'batchAdapterJobParams[0].responseMeta.responseAlias[1]': 'name',
    'batchAdapterJobParams[0].responseMeta.responseAlias[2]': 'created',
    'batchAdapterJobParams[0].responseMeta.responseAlias[3]': 'alertCount',
    'batchAdapterJobParams[0].responseMeta.responseAlias[4]': 'status',
    'batchAdapterJobParams[0].responseMeta.responseAlias[5]': 'assignee.name',
    'batchAdapterJobParams[0].responseMeta.responseAlias[6]': 'priority',
    'batchAdapterJobParams[0].responseMeta.responseAlias[7]': 'averageAlertRiskScore',
    'batchAdapterJobParams[0].lookupParams': null,
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[0].direction': 'DESC',
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[0].propertyName': 'created',
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[1].direction': 'DESC',
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[1].propertyName': 'prioritySort',
    'batchAdapterJobParams[0].queryProperties[0].name': 'alert',
    'batchAdapterJobParams[0].queryProperties[0].groupBy[0]': 'incidentId',
    'batchAdapterJobParams[0].queryProperties[0].joinField': null,
    'batchAdapterJobParams[0].queryProperties[0].filterCriteria': null,
    'batchAdapterJobParams[0].queryProperties[0].condition': null,
    'batchAdapterJobParams[0].queryProperties[0].soapUrlProperties': null,
    'batchAdapterJobParams[0].queryProperties[1].sorting.sortOrder[0].direction': 'DESC',
    'batchAdapterJobParams[0].queryProperties[1].sorting.sortOrder[0].propertyName': 'created',
    'batchAdapterJobParams[0].queryProperties[1].sorting.sortOrder[1].direction': 'DESC',
    'batchAdapterJobParams[0].queryProperties[1].sorting.sortOrder[1].propertyName': 'prioritySort',
    'batchAdapterJobParams[0].queryProperties[1].name': 'incident',
    'batchAdapterJobParams[0].queryProperties[1].groupBy': null,
    'batchAdapterJobParams[0].queryProperties[1].joinField.previous': '_id',
    'batchAdapterJobParams[0].queryProperties[1].joinField.current': '_id',
    'batchAdapterJobParams[0].queryProperties[1].filterCriteria': null,
    'batchAdapterJobParams[0].queryProperties[1].condition': null,
    'batchAdapterJobParams[0].queryProperties[1].soapUrlProperties': null,
    'batchAdapterJobParams[0].previewCount': null,
    'batchAdapterJobParams[1].jobId': 'prefetch',
    'batchAdapterJobParams[1].schedule': '0 0/60 * * * ?',
    'batchAdapterJobParams[1].writePolicy': null,
    'batchAdapterJobParams[1].responseMeta.limit': 0,
    'batchAdapterJobParams[1].responseMeta.pageSize': 1000,
    'batchAdapterJobParams[1].responseMeta.uniqueId': null,
    'batchAdapterJobParams[1].responseMeta.responseAlias[0]': 'alert.timestamp',
    'batchAdapterJobParams[1].responseMeta.responseAlias[1]': 'incidentId',
    'batchAdapterJobParams[1].responseMeta.responseAlias[2]': 'alert.events.source.device.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[3]': 'alert.events.destination.device.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[4]': 'alert.events.detector.device.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[5]': 'alert.events.detector.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[6]': 'alert.events.source.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[7]': 'alert.events.destination.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[8]': 'alert.user',
    'batchAdapterJobParams[1].responseMeta.responseAlias[9]': 'alert.events.user',
    'batchAdapterJobParams[1].responseMeta.responseAlias[10]': 'alert.events.source.user.ad_username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[11]': 'alert.events.destination.user.ad_username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[12]': 'alert.events.source.user.username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[13]': 'alert.events.destination.user.username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[14]': 'alert.events.source.dns_hostname',
    'batchAdapterJobParams[1].responseMeta.responseAlias[15]': 'alert.events.destination.dns_hostname',
    'batchAdapterJobParams[1].responseMeta.responseAlias[16]': 'alert.events.detector.dns_hostname',
    'batchAdapterJobParams[1].responseMeta.responseAlias[17]': 'alert.events.source.device.netbios_name',
    'batchAdapterJobParams[1].responseMeta.responseAlias[18]': 'alert.events.destination.device.netbios_name',
    'batchAdapterJobParams[1].responseMeta.responseAlias[19]': 'alert.events.domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[20]': 'alert.events.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[21]': 'alert.events.source.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[22]': 'alert.events.destination.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[23]': 'alert.events.detector.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[24]': 'alert.events.source.user.ad_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[25]': 'alert.events.destination.user.ad_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[26]': 'alert.events.source.device.geolocation.domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[27]': 'alert.events.destination.device.geolocation.domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[28]': 'alert.events.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[29]': 'alert.events.source.device.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[30]': 'alert.events.destination.device.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[31]': 'alert.events.detector.device.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[32]': 'alert.events.detector.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[33]': 'alert.events.source.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[34]': 'alert.events.destination.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[35]': 'alert.events.file',
    'batchAdapterJobParams[1].responseMeta.responseAlias[36]': 'alert.events.data.filename',
    'batchAdapterJobParams[1].responseMeta.responseAlias[37]': 'alert.events.data.hash',
    'batchAdapterJobParams[1].lookupParams': null,
    'batchAdapterJobParams[1].queryProperties[0].sorting': null,
    'batchAdapterJobParams[1].queryProperties[0].name': 'alert',
    'batchAdapterJobParams[1].queryProperties[0].groupBy': null,
    'batchAdapterJobParams[1].queryProperties[0].joinField': null,
    'batchAdapterJobParams[1].queryProperties[0].filterCriteria': null,
    'batchAdapterJobParams[1].queryProperties[0].condition[0].negate': false,
    'batchAdapterJobParams[1].queryProperties[0].condition[0].fieldName': 'incidentId',
    'batchAdapterJobParams[1].queryProperties[0].condition[0].name': '',
    'batchAdapterJobParams[1].queryProperties[0].condition[0].relationalOp': 'IsNotNull',
    'batchAdapterJobParams[1].queryProperties[0].condition[0].values': null,
    'batchAdapterJobParams[1].queryProperties[0].soapUrlProperties': null,
    'batchAdapterJobParams[1].previewCount': null,
    'batchAdapterJobParams[2].jobId': 'flagging',
    'batchAdapterJobParams[2].schedule': null,
    'batchAdapterJobParams[2].writePolicy': null,
    'batchAdapterJobParams[2].responseMeta.limit': 0,
    'batchAdapterJobParams[2].responseMeta.pageSize': 0,
    'batchAdapterJobParams[2].responseMeta.uniqueId': null,
    'batchAdapterJobParams[2].responseMeta.responseAlias[0]': 'entityName',
    'batchAdapterJobParams[2].responseMeta.responseAlias[1]': 'entityValue',
    'batchAdapterJobParams[2].responseMeta.responseAlias[2]': 'count',
    'batchAdapterJobParams[2].lookupParams': null,
    'batchAdapterJobParams[2].queryProperties': null,
    'batchAdapterJobParams[2].previewCount': null,
    'timeFilter.propertyName': 'incidentCreated',
    'timeFilter.timeUnitCount': 7,
    'timeFilter.absoluteStartTime': true,
    'timeFilter.timeUnit': 'DAY'
  },
  'createdOn': 0,
  'lastModifiedOn': 0
}, {
  'id': '58be7d121969557cbbdbfc58',
  'name': '58be7d121969557cbbdbfc55_Alerts_datasource',
  'enabled': true,
  'description': null,
  'type': 'Alerts',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 13,
  'contentLastModifiedTime': 1488906967370,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'alert.events.source.device.ip_address',
      'remoteFieldName': 'alert.events.source.device.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Source Device IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.ip_address',
      'remoteFieldName': 'alert.events.destination.device.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination Device IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.device.ip_address',
      'remoteFieldName': 'alert.events.detector.device.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector Device IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.ip_address',
      'remoteFieldName': 'alert.events.detector.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.ip_address',
      'remoteFieldName': 'alert.events.source.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Source IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.ip_address',
      'remoteFieldName': 'alert.events.destination.ip_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination IP address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.user',
      'remoteFieldName': 'alert.user',
      'dataType': null,
      'fieldDescription': 'Alert User',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.user',
      'remoteFieldName': 'alert.events.user',
      'dataType': null,
      'fieldDescription': 'Alert User',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.user.ad_username',
      'remoteFieldName': 'alert.events.source.user.ad_username',
      'dataType': null,
      'fieldDescription': 'Alert Source AD User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.user.ad_username',
      'remoteFieldName': 'alert.events.destination.user.ad_username',
      'dataType': null,
      'fieldDescription': 'Alert Destination AD User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.user.username',
      'remoteFieldName': 'alert.events.source.user.username',
      'dataType': null,
      'fieldDescription': 'Alert Source User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.user.username',
      'remoteFieldName': 'alert.events.destination.user.username',
      'dataType': null,
      'fieldDescription': 'Alert Destination User Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.dns_hostname',
      'remoteFieldName': 'alert.events.source.dns_hostname',
      'dataType': null,
      'fieldDescription': 'Alert Source Host Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.dns_hostname',
      'remoteFieldName': 'alert.events.destination.dns_hostname',
      'dataType': null,
      'fieldDescription': 'Alert Destination Host Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.dns_hostname',
      'remoteFieldName': 'alert.events.detector.dns_hostname',
      'dataType': null,
      'fieldDescription': 'Alert Detector Host Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.device.netbios_name',
      'remoteFieldName': 'alert.events.source.device.netbios_name',
      'dataType': null,
      'fieldDescription': 'Alert Source Device NetBIOS Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.netbios_name',
      'remoteFieldName': 'alert.events.destination.device.netbios_name',
      'dataType': null,
      'fieldDescription': 'Alert Destination Device NetBIOS Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.domain',
      'remoteFieldName': 'alert.events.domain',
      'dataType': null,
      'fieldDescription': 'Alert Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.dns_domain',
      'remoteFieldName': 'alert.events.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.dns_domain',
      'remoteFieldName': 'alert.events.source.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert Source DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.dns_domain',
      'remoteFieldName': 'alert.events.destination.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert Destination DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.dns_domain',
      'remoteFieldName': 'alert.events.detector.dns_domain',
      'dataType': null,
      'fieldDescription': 'Alert Detector DNS Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.user.ad_domain',
      'remoteFieldName': 'alert.events.source.user.ad_domain',
      'dataType': null,
      'fieldDescription': 'Alert Source AD Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.user.ad_domain',
      'remoteFieldName': 'alert.events.destination.user.ad_domain',
      'dataType': null,
      'fieldDescription': 'Alert Destination AD Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.device.geolocation.domain',
      'remoteFieldName': 'alert.events.source.device.geolocation.domain',
      'dataType': null,
      'fieldDescription': 'Alert Source Geolocation Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.geolocation.domain',
      'remoteFieldName': 'alert.events.destination.device.geolocation.domain',
      'dataType': null,
      'fieldDescription': 'Alert Destination Geolocation Domain',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.mac_address',
      'remoteFieldName': 'alert.events.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.device.mac_address',
      'remoteFieldName': 'alert.events.source.device.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Source MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.device.mac_address',
      'remoteFieldName': 'alert.events.destination.device.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.device.mac_address',
      'remoteFieldName': 'alert.events.detector.device.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector Device MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.detector.mac_address',
      'remoteFieldName': 'alert.events.detector.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Detector MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.source.mac_address',
      'remoteFieldName': 'alert.events.source.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Source MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.destination.mac_address',
      'remoteFieldName': 'alert.events.destination.mac_address',
      'dataType': null,
      'fieldDescription': 'Alert Destination MAC Address',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.file',
      'remoteFieldName': 'alert.events.file',
      'dataType': null,
      'fieldDescription': 'Alert File Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.data.filename',
      'remoteFieldName': 'alert.events.data.filename',
      'dataType': null,
      'fieldDescription': 'Alert Data File Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.events.data.hash',
      'remoteFieldName': 'alert.events.data.hash',
      'dataType': null,
      'fieldDescription': 'Alert Data Hash',
      'primaryKey': false
    }, {
      'fieldName': 'id',
      'remoteFieldName': 'id',
      'dataType': null,
      'fieldDescription': 'Alert Id',
      'primaryKey': false
    }, {
      'fieldName': 'alert.name',
      'remoteFieldName': 'alert.name',
      'dataType': null,
      'fieldDescription': 'Alert Name',
      'primaryKey': false
    }, {
      'fieldName': 'alert.timestamp',
      'remoteFieldName': 'alert.timestamp',
      'dataType': null,
      'fieldDescription': 'Alert Timestamp',
      'primaryKey': false
    }, {
      'fieldName': 'incidentId',
      'remoteFieldName': 'incidentId',
      'dataType': null,
      'fieldDescription': 'Alert Incident Id',
      'primaryKey': false
    }, {
      'fieldName': 'alert.ruleId',
      'remoteFieldName': 'alert.ruleId',
      'dataType': null,
      'fieldDescription': 'Alert Rule Id',
      'primaryKey': false
    }, {
      'fieldName': 'alert.source',
      'remoteFieldName': 'alert.source',
      'dataType': null,
      'fieldDescription': 'Alert Source',
      'primaryKey': false
    }, {
      'fieldName': 'alert.risk_score',
      'remoteFieldName': 'alert.risk_score',
      'dataType': null,
      'fieldDescription': 'Alert Risk Score',
      'primaryKey': false
    }, {
      'fieldName': 'alert.numEvents',
      'remoteFieldName': 'alert.numEvents',
      'dataType': null,
      'fieldDescription': 'Alert Number of Events',
      'primaryKey': false
    }, {
      'fieldName': 'timeStamp',
      'remoteFieldName': 'timeStamp',
      'dataType': null,
      'fieldDescription': 'Incident Alerts Count',
      'primaryKey': false
    }],
    'entityMapping': {
      'IP': ['alert.events.source.device.ip_address', 'alert.events.destination.device.ip_address', 'alert.events.detector.device.ip_address', 'alert.events.detector.ip_address', 'alert.events.source.ip_address', 'alert.events.destination.ip_address', 'entityValue'],
      'USER': ['alert.user', 'alert.events.user', 'alert.events.source.user.ad_username', 'alert.events.destination.user.ad_username', 'alert.events.source.user.username', 'alert.events.destination.user.username', 'entityValue'],
      'HOST': ['alert.events.source.dns_hostname', 'alert.events.destination.dns_hostname', 'alert.events.detector.dns_hostname', 'alert.events.source.device.netbios_name', 'alert.events.destination.device.netbios_name', 'entityValue'],
      'DOMAIN': ['alert.events.domain', 'alert.events.dns_domain', 'alert.events.source.dns_domain', 'alert.events.destination.dns_domain', 'alert.events.detector.dns_domain', 'alert.events.source.user.ad_domain', 'alert.events.destination.user.ad_domain', 'alert.events.source.device.geolocation.domain', 'alert.events.destination.device.geolocation.domain', 'entityValue'],
      'MAC_ADDRESS': ['alert.events.mac_address', 'alert.events.source.device.mac_address', 'alert.events.destination.device.mac_address', 'alert.events.detector.device.mac_address', 'alert.events.detector.mac_address', 'alert.events.source.mac_address', 'alert.events.destination.mac_address', 'entityValue'],
      'FILE_NAME': ['alert.events.file', 'alert.events.data.filename', 'entityValue'],
      'FILE_HASH': ['alert.events.data.hash', 'entityValue']
    }
  },
  'indexDefinitions': [{
    'indexType': 'TTL',
    'fieldsInIndex': ['timeStamp'],
    'expireAfterSeconds': 604800
  }],
  'dataSourceGroup': 'Alerts',
  'dataSourceConnectionId': '58be7d121969557cbbdbfc55',
  'dataSourceDisplayName': '58be7d121969557cbbdbfc55_Alerts_datasource',
  'tags': [],
  'queryResponseCachePolicy': {
    'enabled': true,
    'maxSizeOfEntryAllowed': '2048 B',
    'maxSecondsInCache': '1800 SECONDS',
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'dataSourceEntriesCachePolicy': {
    'cacheEnabled': true,
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'advancedParameters': {
    'batchAdapterJobParams[0].jobId': 'entityLookup',
    'batchAdapterJobParams[0].schedule': null,
    'batchAdapterJobParams[0].writePolicy': null,
    'batchAdapterJobParams[0].responseMeta.limit': 100,
    'batchAdapterJobParams[0].responseMeta.pageSize': 0,
    'batchAdapterJobParams[0].responseMeta.uniqueId': null,
    'batchAdapterJobParams[0].responseMeta.responseAlias[0]': 'id',
    'batchAdapterJobParams[0].responseMeta.responseAlias[1]': 'alert.name',
    'batchAdapterJobParams[0].responseMeta.responseAlias[2]': 'alert.timestamp',
    'batchAdapterJobParams[0].responseMeta.responseAlias[3]': 'incidentId',
    'batchAdapterJobParams[0].responseMeta.responseAlias[4]': 'alert.ruleId',
    'batchAdapterJobParams[0].responseMeta.responseAlias[5]': 'alert.source',
    'batchAdapterJobParams[0].responseMeta.responseAlias[6]': 'alert.risk_score',
    'batchAdapterJobParams[0].responseMeta.responseAlias[7]': 'alert.numEvents',
    'batchAdapterJobParams[0].lookupParams': null,
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[0].direction': 'DESC',
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[0].propertyName': 'receivedTime',
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[1].direction': 'DESC',
    'batchAdapterJobParams[0].queryProperties[0].sorting.sortOrder[1].propertyName': 'prioritySort',
    'batchAdapterJobParams[0].queryProperties[0].name': 'alert',
    'batchAdapterJobParams[0].queryProperties[0].groupBy': null,
    'batchAdapterJobParams[0].queryProperties[0].joinField': null,
    'batchAdapterJobParams[0].queryProperties[0].filterCriteria': null,
    'batchAdapterJobParams[0].queryProperties[0].condition': null,
    'batchAdapterJobParams[0].queryProperties[0].soapUrlProperties': null,
    'batchAdapterJobParams[0].previewCount': null,
    'batchAdapterJobParams[1].jobId': 'prefetch',
    'batchAdapterJobParams[1].schedule': '0 0/60 * * * ?',
    'batchAdapterJobParams[1].writePolicy': null,
    'batchAdapterJobParams[1].responseMeta.limit': 0,
    'batchAdapterJobParams[1].responseMeta.pageSize': 1000,
    'batchAdapterJobParams[1].responseMeta.uniqueId': null,
    'batchAdapterJobParams[1].responseMeta.responseAlias[0]': 'alert.timestamp',
    'batchAdapterJobParams[1].responseMeta.responseAlias[1]': 'alert.events.source.device.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[2]': 'alert.events.destination.device.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[3]': 'alert.events.detector.device.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[4]': 'alert.events.detector.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[5]': 'alert.events.source.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[6]': 'alert.events.destination.ip_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[7]': 'alert.user',
    'batchAdapterJobParams[1].responseMeta.responseAlias[8]': 'alert.events.user',
    'batchAdapterJobParams[1].responseMeta.responseAlias[9]': 'alert.events.source.user.ad_username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[10]': 'alert.events.destination.user.ad_username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[11]': 'alert.events.source.user.username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[12]': 'alert.events.destination.user.username',
    'batchAdapterJobParams[1].responseMeta.responseAlias[13]': 'alert.events.source.dns_hostname',
    'batchAdapterJobParams[1].responseMeta.responseAlias[14]': 'alert.events.destination.dns_hostname',
    'batchAdapterJobParams[1].responseMeta.responseAlias[15]': 'alert.events.detector.dns_hostname',
    'batchAdapterJobParams[1].responseMeta.responseAlias[16]': 'alert.events.source.device.netbios_name',
    'batchAdapterJobParams[1].responseMeta.responseAlias[17]': 'alert.events.destination.device.netbios_name',
    'batchAdapterJobParams[1].responseMeta.responseAlias[18]': 'alert.events.domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[19]': 'alert.events.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[20]': 'alert.events.source.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[21]': 'alert.events.destination.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[22]': 'alert.events.detector.dns_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[23]': 'alert.events.source.user.ad_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[24]': 'alert.events.destination.user.ad_domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[25]': 'alert.events.source.device.geolocation.domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[26]': 'alert.events.destination.device.geolocation.domain',
    'batchAdapterJobParams[1].responseMeta.responseAlias[27]': 'alert.events.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[28]': 'alert.events.source.device.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[29]': 'alert.events.destination.device.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[30]': 'alert.events.detector.device.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[31]': 'alert.events.detector.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[32]': 'alert.events.source.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[33]': 'alert.events.destination.mac_address',
    'batchAdapterJobParams[1].responseMeta.responseAlias[34]': 'alert.events.file',
    'batchAdapterJobParams[1].responseMeta.responseAlias[35]': 'alert.events.data.filename',
    'batchAdapterJobParams[1].responseMeta.responseAlias[36]': 'alert.events.data.hash',
    'batchAdapterJobParams[1].lookupParams': null,
    'batchAdapterJobParams[1].queryProperties[0].sorting': null,
    'batchAdapterJobParams[1].queryProperties[0].name': 'alert',
    'batchAdapterJobParams[1].queryProperties[0].groupBy': null,
    'batchAdapterJobParams[1].queryProperties[0].joinField': null,
    'batchAdapterJobParams[1].queryProperties[0].filterCriteria': null,
    'batchAdapterJobParams[1].queryProperties[0].condition': null,
    'batchAdapterJobParams[1].queryProperties[0].soapUrlProperties': null,
    'batchAdapterJobParams[1].previewCount': null,
    'batchAdapterJobParams[2].jobId': 'flagging',
    'batchAdapterJobParams[2].schedule': null,
    'batchAdapterJobParams[2].writePolicy': null,
    'batchAdapterJobParams[2].responseMeta.limit': 0,
    'batchAdapterJobParams[2].responseMeta.pageSize': 0,
    'batchAdapterJobParams[2].responseMeta.uniqueId': null,
    'batchAdapterJobParams[2].responseMeta.responseAlias[0]': 'entityName',
    'batchAdapterJobParams[2].responseMeta.responseAlias[1]': 'entityValue',
    'batchAdapterJobParams[2].responseMeta.responseAlias[2]': 'count',
    'batchAdapterJobParams[2].lookupParams': null,
    'batchAdapterJobParams[2].queryProperties': null,
    'batchAdapterJobParams[2].previewCount': null,
    'timeFilter.propertyName': 'alert.timestamp',
    'timeFilter.timeUnitCount': 7,
    'timeFilter.absoluteStartTime': true,
    'timeFilter.timeUnit': 'DAY'
  },
  'createdOn': 0,
  'lastModifiedOn': 0
}, {
  'id': '58be7d911969557cbbdbfc66',
  'name': '58be7d911969557cbbdbfc65_Users_datasource',
  'enabled': true,
  'description': null,
  'type': 'Users',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 0,
  'contentLastModifiedTime': 0,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'objectGUID',
      'remoteFieldName': 'objectGUID',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'sAMAccountName',
      'remoteFieldName': 'sAMAccountName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'objectSid',
      'remoteFieldName': 'objectSid',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'objectClass',
      'remoteFieldName': 'objectClass',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'memberOf',
      'remoteFieldName': 'memberOf',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'distinguishedName',
      'remoteFieldName': 'distinguishedName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'name',
      'remoteFieldName': 'name',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'cn',
      'remoteFieldName': 'cn',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'thumbnailPhoto',
      'remoteFieldName': 'thumbnailPhoto',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'userPrincipalName',
      'remoteFieldName': 'userPrincipalName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'displayName',
      'remoteFieldName': 'displayName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'givenName',
      'remoteFieldName': 'givenName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'middleName',
      'remoteFieldName': 'middleName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'sn',
      'remoteFieldName': 'sn',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'employeeID',
      'remoteFieldName': 'employeeID',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'securityIdentifier',
      'remoteFieldName': 'securityIdentifier',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'primaryGroupID',
      'remoteFieldName': 'primaryGroupID',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'groupMembershipSAM',
      'remoteFieldName': 'groupMembershipSAM',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'sAMAccountType',
      'remoteFieldName': 'sAMAccountType',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'isPrivilegeHolder',
      'remoteFieldName': 'isPrivilegeHolder',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'ou',
      'remoteFieldName': 'ou',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'preferredOU',
      'remoteFieldName': 'preferredOU',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'company',
      'remoteFieldName': 'company',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'division',
      'remoteFieldName': 'division',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'description',
      'remoteFieldName': 'description',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'department',
      'remoteFieldName': 'department',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'mail',
      'remoteFieldName': 'mail',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'telephoneNumber',
      'remoteFieldName': 'telephoneNumber',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'title',
      'remoteFieldName': 'title',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'physicalDeliveryOfficeName',
      'remoteFieldName': 'physicalDeliveryOfficeName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'postalAddress',
      'remoteFieldName': 'postalAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'postalCode',
      'remoteFieldName': 'postalCode',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'co',
      'remoteFieldName': 'co',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'countryCode',
      'remoteFieldName': 'countryCode',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'localeID',
      'remoteFieldName': 'localeID',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'manager',
      'remoteFieldName': 'manager',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'directReports',
      'remoteFieldName': 'directReports',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'pwdLastSet',
      'remoteFieldName': 'pwdLastSet',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'userWorkstations',
      'remoteFieldName': 'userWorkstations',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'uSNChanged',
      'remoteFieldName': 'uSNChanged',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }],
    'entityMapping': {
      'USER': ['sAMAccountName', 'userPrincipalName']
    }
  },
  'indexDefinitions': null,
  'dataSourceGroup': 'Users',
  'dataSourceConnectionId': '58be7d911969557cbbdbfc65',
  'dataSourceDisplayName': '58be7d911969557cbbdbfc65_Users_datasource',
  'tags': [],
  'queryResponseCachePolicy': {
    'enabled': true,
    'maxSizeOfEntryAllowed': '2048 B',
    'maxSecondsInCache': '1800 SECONDS',
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'dataSourceEntriesCachePolicy': {
    'cacheEnabled': true,
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'advancedParameters': {
    'batchAdapterJobParams[0].jobId': 'entityLookup',
    'batchAdapterJobParams[0].schedule': null,
    'batchAdapterJobParams[0].writePolicy': null,
    'batchAdapterJobParams[0].responseMeta.limit': 5,
    'batchAdapterJobParams[0].responseMeta.pageSize': 250,
    'batchAdapterJobParams[0].responseMeta.uniqueId': null,
    'batchAdapterJobParams[0].responseMeta.responseAlias[0]': 'objectGUID',
    'batchAdapterJobParams[0].responseMeta.responseAlias[1]': 'sAMAccountName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[2]': 'objectSid',
    'batchAdapterJobParams[0].responseMeta.responseAlias[3]': 'objectClass',
    'batchAdapterJobParams[0].responseMeta.responseAlias[4]': 'cn',
    'batchAdapterJobParams[0].responseMeta.responseAlias[5]': 'name',
    'batchAdapterJobParams[0].responseMeta.responseAlias[6]': 'thumbnailPhoto',
    'batchAdapterJobParams[0].responseMeta.responseAlias[7]': 'userPrincipalName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[8]': 'displayName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[9]': 'givenName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[10]': 'middleName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[11]': 'sn',
    'batchAdapterJobParams[0].responseMeta.responseAlias[12]': 'employeeID',
    'batchAdapterJobParams[0].responseMeta.responseAlias[13]': 'securityIdentifier',
    'batchAdapterJobParams[0].responseMeta.responseAlias[14]': 'memberOf',
    'batchAdapterJobParams[0].responseMeta.responseAlias[15]': 'primaryGroupID',
    'batchAdapterJobParams[0].responseMeta.responseAlias[16]': 'groupMembershipSAM',
    'batchAdapterJobParams[0].responseMeta.responseAlias[17]': 'isPrivilegeHolder',
    'batchAdapterJobParams[0].responseMeta.responseAlias[18]': 'ou',
    'batchAdapterJobParams[0].responseMeta.responseAlias[19]': 'preferredOU',
    'batchAdapterJobParams[0].responseMeta.responseAlias[20]': 'company',
    'batchAdapterJobParams[0].responseMeta.responseAlias[21]': 'division',
    'batchAdapterJobParams[0].responseMeta.responseAlias[22]': 'description',
    'batchAdapterJobParams[0].responseMeta.responseAlias[23]': 'department',
    'batchAdapterJobParams[0].responseMeta.responseAlias[24]': 'mail',
    'batchAdapterJobParams[0].responseMeta.responseAlias[25]': 'telephoneNumber',
    'batchAdapterJobParams[0].responseMeta.responseAlias[26]': 'sAMAccountType',
    'batchAdapterJobParams[0].responseMeta.responseAlias[27]': 'personalTitle',
    'batchAdapterJobParams[0].responseMeta.responseAlias[28]': 'title',
    'batchAdapterJobParams[0].responseMeta.responseAlias[29]': 'physicalDeliveryOfficeName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[30]': 'postalAddress',
    'batchAdapterJobParams[0].responseMeta.responseAlias[31]': 'postalCode',
    'batchAdapterJobParams[0].responseMeta.responseAlias[32]': 'co',
    'batchAdapterJobParams[0].responseMeta.responseAlias[33]': 'countryCode',
    'batchAdapterJobParams[0].responseMeta.responseAlias[34]': 'localeID',
    'batchAdapterJobParams[0].responseMeta.responseAlias[35]': 'manager',
    'batchAdapterJobParams[0].responseMeta.responseAlias[36]': 'directReports',
    'batchAdapterJobParams[0].responseMeta.responseAlias[37]': 'pwdLastSet',
    'batchAdapterJobParams[0].responseMeta.responseAlias[38]': 'userWorkstations',
    'batchAdapterJobParams[0].responseMeta.responseAlias[39]': 'uSNChanged',
    'batchAdapterJobParams[0].lookupParams': null,
    'batchAdapterJobParams[0].queryProperties[0].sorting': null,
    'batchAdapterJobParams[0].queryProperties[0].name': null,
    'batchAdapterJobParams[0].queryProperties[0].groupBy': null,
    'batchAdapterJobParams[0].queryProperties[0].joinField': null,
    'batchAdapterJobParams[0].queryProperties[0].filterCriteria': '(&(objectClass=top)(objectClass=user)(objectClass=organizationalPerson)(objectClass=person)(!(objectClass=computer)))',
    'batchAdapterJobParams[0].queryProperties[0].condition': null,
    'batchAdapterJobParams[0].queryProperties[0].soapUrlProperties': null,
    'batchAdapterJobParams[0].previewCount': null,
    'timeFilter': null
  },
  'createdOn': 0,
  'lastModifiedOn': 0
}, {
  'id': '58be7cea1969557cbbdbfc42',
  'name': '58be7cea1969557cbbdbfc3f_IOC_datasource',
  'enabled': true,
  'description': null,
  'type': 'IOC',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 0,
  'contentLastModifiedTime': 0,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'IPAddress',
      'remoteFieldName': 'IPAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MacAddress',
      'remoteFieldName': 'MacAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MachineName',
      'remoteFieldName': 'MachineName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Alertable',
      'remoteFieldName': 'Alertable',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'EvaluationDate',
      'remoteFieldName': 'EvaluationDate',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCContext',
      'remoteFieldName': 'IOCContext',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCTriggeredOnMachine',
      'remoteFieldName': 'IOCTriggeredOnMachine',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'BiasStatus',
      'remoteFieldName': 'BiasStatus',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Active',
      'remoteFieldName': 'Active',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Description',
      'remoteFieldName': 'Description',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Type',
      'remoteFieldName': 'Type',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCLevel',
      'remoteFieldName': 'IOCLevel',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'LastExecuted',
      'remoteFieldName': 'LastExecuted',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Name',
      'remoteFieldName': 'Name',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Priority',
      'remoteFieldName': 'Priority',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Query',
      'remoteFieldName': 'Query',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MachineCount',
      'remoteFieldName': 'MachineCount',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'ModuleCount',
      'remoteFieldName': 'ModuleCount',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }],
    'entityMapping': {
      'IP': ['IPAddress'],
      'MAC_ADDRESS': ['MacAddress'],
      'HOST': ['MachineName']
    }
  },
  'indexDefinitions': null,
  'dataSourceGroup': 'IOC',
  'dataSourceConnectionId': '58be7cea1969557cbbdbfc3f',
  'dataSourceDisplayName': '58be7cea1969557cbbdbfc3f_IOC_datasource',
  'tags': [],
  'queryResponseCachePolicy': {
    'enabled': true,
    'maxSizeOfEntryAllowed': '2048 B',
    'maxSecondsInCache': '1800 SECONDS',
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'dataSourceEntriesCachePolicy': {
    'cacheEnabled': true,
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'advancedParameters': {
    'batchAdapterJobParams[0].jobId': 'entityLookup',
    'batchAdapterJobParams[0].schedule': null,
    'batchAdapterJobParams[0].writePolicy': null,
    'batchAdapterJobParams[0].responseMeta.limit': 5,
    'batchAdapterJobParams[0].responseMeta.pageSize': 250,
    'batchAdapterJobParams[0].responseMeta.uniqueId': null,
    'batchAdapterJobParams[0].responseMeta.responseAlias[0]': 'Name',
    'batchAdapterJobParams[0].responseMeta.responseAlias[1]': 'Alertable',
    'batchAdapterJobParams[0].responseMeta.responseAlias[2]': 'EvaluationDate',
    'batchAdapterJobParams[0].responseMeta.responseAlias[3]': 'IOCContext',
    'batchAdapterJobParams[0].responseMeta.responseAlias[4]': 'IOCTriggeredOnMachine',
    'batchAdapterJobParams[0].responseMeta.responseAlias[5]': 'BiasStatus',
    'batchAdapterJobParams[0].responseMeta.responseAlias[6]': 'Active',
    'batchAdapterJobParams[0].responseMeta.responseAlias[7]': 'Description',
    'batchAdapterJobParams[0].responseMeta.responseAlias[8]': 'Type',
    'batchAdapterJobParams[0].responseMeta.responseAlias[9]': 'IOCLevel',
    'batchAdapterJobParams[0].responseMeta.responseAlias[10]': 'LastExecuted',
    'batchAdapterJobParams[0].responseMeta.responseAlias[11]': 'Priority',
    'batchAdapterJobParams[0].responseMeta.responseAlias[12]': 'Query',
    'batchAdapterJobParams[0].responseMeta.responseAlias[13]': 'MachineCount',
    'batchAdapterJobParams[0].responseMeta.responseAlias[14]': 'ModuleCount',
    'batchAdapterJobParams[0].lookupParams[0].id': 'guidstep',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.url': '/api/v2/machines?{LIST}',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.inputMeta': '',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.separator': '=',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[0].body[0].mapper': 'Items[0].Id',
    'batchAdapterJobParams[0].lookupParams[0].body[0].carryForwardMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[0].body[0].responseMeta': '',
    'batchAdapterJobParams[0].lookupParams[0].body[0].rootResponseKey': '',
    'batchAdapterJobParams[0].lookupParams[0].header': null,
    'batchAdapterJobParams[0].lookupParams[0].additionalResponse': null,
    'batchAdapterJobParams[0].lookupParams[0].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.name': 'guidStep',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].name': 'format',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].lookupParams[1].id': 'iocsStep',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.url': '/api/v2/machines/{0}/instantiocs',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.inputMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.separator': null,
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[1].body[0].mapper': 'Iocs',
    'batchAdapterJobParams[0].lookupParams[1].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[0].lookupParams[1].body[0].responseMeta': 'details',
    'batchAdapterJobParams[0].lookupParams[1].body[0].rootResponseKey': null,
    'batchAdapterJobParams[0].lookupParams[1].header': null,
    'batchAdapterJobParams[0].lookupParams[1].additionalResponse': null,
    'batchAdapterJobParams[0].lookupParams[1].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.name': 'iocStep',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].name': 'format',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].queryProperties': null,
    'batchAdapterJobParams[0].previewCount': null,
    'timeFilter': null
  },
  'createdOn': 0,
  'lastModifiedOn': 0
}, {
  'id': '58be7cea1969557cbbdbfc41',
  'name': '58be7cea1969557cbbdbfc3f_Modules_datasource',
  'enabled': true,
  'description': null,
  'type': 'Modules',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 0,
  'contentLastModifiedTime': 0,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'IPAddress',
      'remoteFieldName': 'IPAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MacAddress',
      'remoteFieldName': 'MacAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MachineName',
      'remoteFieldName': 'MachineName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Name',
      'remoteFieldName': 'Name',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'ModuleName',
      'remoteFieldName': 'ModuleName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCScore',
      'remoteFieldName': 'IOCScore',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCLevel0',
      'remoteFieldName': 'IOCLevel0',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCLevel1',
      'remoteFieldName': 'IOCLevel1',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCLevel2',
      'remoteFieldName': 'IOCLevel2',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IOCLevel3',
      'remoteFieldName': 'IOCLevel3',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Signature',
      'remoteFieldName': 'Signature',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'AnalyticsScore',
      'remoteFieldName': 'AnalyticsScore',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'BiasStatusComment',
      'remoteFieldName': 'BiasStatusComment',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'BiasStatusEnum',
      'remoteFieldName': 'BiasStatusEnum',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'GlobalMachineCount',
      'remoteFieldName': 'GlobalMachineCount',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'HashMD5',
      'remoteFieldName': 'HashMD5',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'HashSHA1',
      'remoteFieldName': 'HashSHA1',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'HashSHA256',
      'remoteFieldName': 'HashSHA256',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'FileName',
      'remoteFieldName': 'FileName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Path',
      'remoteFieldName': 'Path',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }],
    'entityMapping': {
      'IP': ['IPAddress'],
      'MAC_ADDRESS': ['MacAddress'],
      'HOST': ['MachineName']
    }
  },
  'indexDefinitions': null,
  'dataSourceGroup': 'Modules',
  'dataSourceConnectionId': '58be7cea1969557cbbdbfc3f',
  'dataSourceDisplayName': '58be7cea1969557cbbdbfc3f_Modules_datasource',
  'tags': [],
  'queryResponseCachePolicy': {
    'enabled': true,
    'maxSizeOfEntryAllowed': '2048 B',
    'maxSecondsInCache': '1800 SECONDS',
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'dataSourceEntriesCachePolicy': {
    'cacheEnabled': true,
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'advancedParameters': {
    'batchAdapterJobParams[0].jobId': 'entityLookup',
    'batchAdapterJobParams[0].schedule': null,
    'batchAdapterJobParams[0].writePolicy': null,
    'batchAdapterJobParams[0].responseMeta.limit': 5,
    'batchAdapterJobParams[0].responseMeta.pageSize': 250,
    'batchAdapterJobParams[0].responseMeta.uniqueId': null,
    'batchAdapterJobParams[0].responseMeta.responseAlias[0]': 'Name',
    'batchAdapterJobParams[0].responseMeta.responseAlias[1]': 'ModuleName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[2]': 'IOCScore',
    'batchAdapterJobParams[0].responseMeta.responseAlias[3]': 'IOCLevel0',
    'batchAdapterJobParams[0].responseMeta.responseAlias[4]': 'IOCLevel1',
    'batchAdapterJobParams[0].responseMeta.responseAlias[5]': 'IOCLevel2',
    'batchAdapterJobParams[0].responseMeta.responseAlias[6]': 'IOCLevel3',
    'batchAdapterJobParams[0].responseMeta.responseAlias[7]': 'Signature',
    'batchAdapterJobParams[0].responseMeta.responseAlias[8]': 'AnalyticsScore',
    'batchAdapterJobParams[0].responseMeta.responseAlias[9]': 'BiasStatusEnum',
    'batchAdapterJobParams[0].responseMeta.responseAlias[10]': 'BiasStatusComment',
    'batchAdapterJobParams[0].responseMeta.responseAlias[11]': 'GlobalMachineCount',
    'batchAdapterJobParams[0].responseMeta.responseAlias[12]': 'HashSHA256',
    'batchAdapterJobParams[0].responseMeta.responseAlias[13]': 'HashSHA1',
    'batchAdapterJobParams[0].responseMeta.responseAlias[14]': 'HashMD5',
    'batchAdapterJobParams[0].responseMeta.responseAlias[15]': 'Path',
    'batchAdapterJobParams[0].responseMeta.responseAlias[16]': 'FileName',
    'batchAdapterJobParams[0].lookupParams[0].id': 'guidstep',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.url': '/api/v2/machines?{LIST}',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.inputMeta': '',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.separator': '=',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[0].body[0].mapper': 'Items[0].Id',
    'batchAdapterJobParams[0].lookupParams[0].body[0].carryForwardMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[0].body[0].responseMeta': '',
    'batchAdapterJobParams[0].lookupParams[0].body[0].rootResponseKey': '',
    'batchAdapterJobParams[0].lookupParams[0].header': null,
    'batchAdapterJobParams[0].lookupParams[0].additionalResponse': null,
    'batchAdapterJobParams[0].lookupParams[0].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.name': 'guidStep',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].name': 'format',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].lookupParams[1].id': 'moduleCountStep',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.url': '/api/v2/machines/{0}/modules?Properties=ModuleName,IOCScore,IOCLevel0,IOCLevel1,IOCLevel2,IOCLevel3,Signature,AnalyticsScore,BiasStatusComment,BiasStatusEnum,GlobalMachineCount,HashMD5,HashSHA1,HashSHA256,FileName,Path',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.inputMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.separator': null,
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[1].body': null,
    'batchAdapterJobParams[0].lookupParams[1].header[0].mapper': 'x-total-count',
    'batchAdapterJobParams[0].lookupParams[1].header[0].carryForwardMeta': '',
    'batchAdapterJobParams[0].lookupParams[1].header[0].responseMeta': 'total_modules_count',
    'batchAdapterJobParams[0].lookupParams[1].header[0].rootResponseKey': '',
    'batchAdapterJobParams[0].lookupParams[1].additionalResponse': null,
    'batchAdapterJobParams[0].lookupParams[1].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.name': 'moduleCount',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].name': 'format',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[1].negate': false,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[1].fieldName': 'per_page',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[1].name': 'per_page',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[1].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[1].values[0]': 1,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].lookupParams[2].id': 'moduleDetailStep',
    'batchAdapterJobParams[0].lookupParams[2].urlProperties.url': '/api/v2/machines/{0}/modules?Properties=ModuleName,IOCScore,IOCLevel0,IOCLevel1,IOCLevel2,IOCLevel3,Signature,AnalyticsScore,BiasStatusComment,BiasStatusEnum,GlobalMachineCount,HashMD5,HashSHA1,HashSHA256,FileName,Path',
    'batchAdapterJobParams[0].lookupParams[2].urlProperties.inputMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[2].urlProperties.separator': null,
    'batchAdapterJobParams[0].lookupParams[2].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[2].body[0].mapper': '$.Items[*].Properties',
    'batchAdapterJobParams[0].lookupParams[2].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[0].lookupParams[2].body[0].responseMeta': 'details',
    'batchAdapterJobParams[0].lookupParams[2].body[0].rootResponseKey': null,
    'batchAdapterJobParams[0].lookupParams[2].header': null,
    'batchAdapterJobParams[0].lookupParams[2].additionalResponse[0]': 'iocScore_gte',
    'batchAdapterJobParams[0].lookupParams[2].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.name': 'moduleDetail',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[0].fieldName': 'iocScore_gte',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[0].name': 'iocScore_gte',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[0].values[0]': 500,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[1].negate': false,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[1].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[1].name': 'format',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[1].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[1].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[2].negate': false,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[2].fieldName': 'per_page',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[2].name': 'limit',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[2].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.condition[2].values[0]': 500,
    'batchAdapterJobParams[0].lookupParams[2].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].queryProperties': null,
    'batchAdapterJobParams[0].previewCount': null,
    'timeFilter': null
  },
  'createdOn': 0,
  'lastModifiedOn': 0
}, {
  'id': '58be7e251969557cbbdbfc6e',
  'name': 'List',
  'enabled': true,
  'description': '',
  'type': 'LIST',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 1,
  'contentLastModifiedTime': 1488879141769,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'LIST',
      'remoteFieldName': 'LIST',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }],
    'entityMapping': {
      'FILE_HASH': ['LIST'],
      'DOMAIN': ['LIST'],
      'IP': ['LIST'],
      'HOST': ['LIST'],
      'USER': ['LIST'],
      'FILE_NAME': ['LIST'],
      'MAC_ADDRESS': ['LIST']
    }
  },
  'indexDefinitions': null,
  'dataSourceGroup': 'LIST',
  'dataSourceConnectionId': null,
  'dataSourceDisplayName': 'List',
  'tags': ['LIST'],
  'queryResponseCachePolicy': null,
  'dataSourceEntriesCachePolicy': null,
  'advancedParameters': {},
  'createdOn': 0,
  'lastModifiedOn': 0
}, {
  'id': '58be7cea1969557cbbdbfc40',
  'name': '58be7cea1969557cbbdbfc3f_Machines_datasource',
  'enabled': true,
  'description': null,
  'type': 'Machines',
  'maxSize': -1,
  'maxAgeOfEntriesInSeconds': -1,
  'maxStorageSize': -1,
  'maxCacheMemorySize': -1,
  'contentVersion': 21,
  'contentLastModifiedTime': 1488907474400,
  'schema': {
    'schemaEntries': [{
      'fieldName': 'LocalIPAddress',
      'remoteFieldName': 'LocalIP',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IPAddress',
      'remoteFieldName': 'IPAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'AgentID',
      'remoteFieldName': 'AgentID',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'RemoteIPAddress',
      'remoteFieldName': 'RemoteIp',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'RemoteIP',
      'remoteFieldName': 'RemoteIP',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MAC',
      'remoteFieldName': 'MAC',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MachineName',
      'remoteFieldName': 'MachineName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MacAddress',
      'remoteFieldName': 'MacAddress',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Name',
      'remoteFieldName': 'Name',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MachineStatus',
      'remoteFieldName': 'MachineStatus',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'MachineID',
      'remoteFieldName': 'MachineID',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'ServicePackOS',
      'remoteFieldName': 'ServicePackOS',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'VersionInfo',
      'remoteFieldName': 'VersionInfo',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IIOCScore',
      'remoteFieldName': 'IIOCScore',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IIOCLevel0',
      'remoteFieldName': 'IIOCLevel0',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IIOCLevel1',
      'remoteFieldName': 'IIOCLevel1',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IIOCLevel2',
      'remoteFieldName': 'IIOCLevel2',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'IIOCLevel3',
      'remoteFieldName': 'IIOCLevel3',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'OperatingSystem',
      'remoteFieldName': 'OperatingSystem',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Online',
      'remoteFieldName': 'Online',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Comment',
      'remoteFieldName': 'Comment',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'LastSeen',
      'remoteFieldName': 'LastSeen',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'UserName',
      'remoteFieldName': 'UserName',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'NetworkSegment',
      'remoteFieldName': 'NetworkSegment',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'AdminStatus',
      'remoteFieldName': 'AdminStatus',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Gateway',
      'remoteFieldName': 'Gateway',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'OrganizationUnit',
      'remoteFieldName': 'OrganizationUnit',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'DNS',
      'remoteFieldName': 'DNS',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'FirewallDisabled',
      'remoteFieldName': 'FirewallDisabled',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'TimeZone',
      'remoteFieldName': 'TimeZone',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Platform',
      'remoteFieldName': 'Platform',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'LastScan',
      'remoteFieldName': 'LastScan',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'BootTime',
      'remoteFieldName': 'BootTime',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Country',
      'remoteFieldName': 'Country',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }, {
      'fieldName': 'Serial',
      'remoteFieldName': 'Serial',
      'dataType': null,
      'fieldDescription': null,
      'primaryKey': false
    }],
    'entityMapping': {
      'IP': ['IPAddress', 'RemoteIPAddress'],
      'MAC_ADDRESS': ['MacAddress'],
      'HOST': ['MachineName', 'Name']
    }
  },
  'indexDefinitions': null,
  'dataSourceGroup': 'Machines',
  'dataSourceConnectionId': '58be7cea1969557cbbdbfc3f',
  'dataSourceDisplayName': '58be7cea1969557cbbdbfc3f_Machines_datasource',
  'tags': [],
  'queryResponseCachePolicy': {
    'enabled': true,
    'maxSizeOfEntryAllowed': '2048 B',
    'maxSecondsInCache': '1800 SECONDS',
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'dataSourceEntriesCachePolicy': {
    'cacheEnabled': true,
    'maxSizeOfCacheBytes': '1048576 B'
  },
  'advancedParameters': {
    'batchAdapterJobParams[0].jobId': 'entityLookup',
    'batchAdapterJobParams[0].schedule': null,
    'batchAdapterJobParams[0].writePolicy': null,
    'batchAdapterJobParams[0].responseMeta.limit': 0,
    'batchAdapterJobParams[0].responseMeta.pageSize': 250,
    'batchAdapterJobParams[0].responseMeta.uniqueId': null,
    'batchAdapterJobParams[0].responseMeta.responseAlias[0]': 'LocalIPAddress',
    'batchAdapterJobParams[0].responseMeta.responseAlias[1]': 'RemoteIP',
    'batchAdapterJobParams[0].responseMeta.responseAlias[2]': 'MAC',
    'batchAdapterJobParams[0].responseMeta.responseAlias[3]': 'MachineName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[4]': 'MachineStatus',
    'batchAdapterJobParams[0].responseMeta.responseAlias[5]': 'MachineID',
    'batchAdapterJobParams[0].responseMeta.responseAlias[6]': 'ServicePackOS',
    'batchAdapterJobParams[0].responseMeta.responseAlias[7]': 'Serial',
    'batchAdapterJobParams[0].responseMeta.responseAlias[8]': 'Country',
    'batchAdapterJobParams[0].responseMeta.responseAlias[9]': 'BootTime',
    'batchAdapterJobParams[0].responseMeta.responseAlias[10]': 'LastScan',
    'batchAdapterJobParams[0].responseMeta.responseAlias[11]': 'Platform',
    'batchAdapterJobParams[0].responseMeta.responseAlias[12]': 'TimeZone',
    'batchAdapterJobParams[0].responseMeta.responseAlias[13]': 'FirewallDisabled',
    'batchAdapterJobParams[0].responseMeta.responseAlias[14]': 'DNS',
    'batchAdapterJobParams[0].responseMeta.responseAlias[15]': 'OrganizationUnit',
    'batchAdapterJobParams[0].responseMeta.responseAlias[16]': 'Gateway',
    'batchAdapterJobParams[0].responseMeta.responseAlias[17]': 'AdminStatus',
    'batchAdapterJobParams[0].responseMeta.responseAlias[18]': 'NetworkSegment',
    'batchAdapterJobParams[0].responseMeta.responseAlias[19]': 'UserName',
    'batchAdapterJobParams[0].responseMeta.responseAlias[20]': 'LastSeen',
    'batchAdapterJobParams[0].responseMeta.responseAlias[21]': 'Comment',
    'batchAdapterJobParams[0].responseMeta.responseAlias[22]': 'Online',
    'batchAdapterJobParams[0].responseMeta.responseAlias[23]': 'OperatingSystem',
    'batchAdapterJobParams[0].responseMeta.responseAlias[24]': 'IIOCLevel3',
    'batchAdapterJobParams[0].responseMeta.responseAlias[25]': 'IIOCLevel2',
    'batchAdapterJobParams[0].responseMeta.responseAlias[26]': 'IIOCLevel1',
    'batchAdapterJobParams[0].responseMeta.responseAlias[27]': 'IIOCLevel0',
    'batchAdapterJobParams[0].responseMeta.responseAlias[28]': 'IIOCScore',
    'batchAdapterJobParams[0].responseMeta.responseAlias[29]': 'VersionInfo',
    'batchAdapterJobParams[0].lookupParams[0].id': 'guidstep',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.url': '/api/v2/machines?{LIST}',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.inputMeta': '',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.separator': '=',
    'batchAdapterJobParams[0].lookupParams[0].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[0].body[0].mapper': 'Items[0].Id',
    'batchAdapterJobParams[0].lookupParams[0].body[0].carryForwardMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[0].body[0].responseMeta': '',
    'batchAdapterJobParams[0].lookupParams[0].body[0].rootResponseKey': '',
    'batchAdapterJobParams[0].lookupParams[0].header': null,
    'batchAdapterJobParams[0].lookupParams[0].additionalResponse': null,
    'batchAdapterJobParams[0].lookupParams[0].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.name': 'guidStep',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].name': 'format',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.condition[0].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[0].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].lookupParams[1].id': 'machinestep',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.url': '/api/v2/machines/{0}',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.inputMeta': 'guid',
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.separator': null,
    'batchAdapterJobParams[0].lookupParams[1].urlProperties.uriMeta': null,
    'batchAdapterJobParams[0].lookupParams[1].body[0].mapper': 'Machine',
    'batchAdapterJobParams[0].lookupParams[1].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[0].lookupParams[1].body[0].responseMeta': 'details',
    'batchAdapterJobParams[0].lookupParams[1].body[0].rootResponseKey': null,
    'batchAdapterJobParams[0].lookupParams[1].header': null,
    'batchAdapterJobParams[0].lookupParams[1].additionalResponse': null,
    'batchAdapterJobParams[0].lookupParams[1].additionalParams': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.sorting': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.name': 'machineStep',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.groupBy': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.joinField': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.filterCriteria': null,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].negate': false,
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].fieldName': 'format',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].name': 'format',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].relationalOp': 'Equal',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.condition[0].values[0]': 'json',
    'batchAdapterJobParams[0].lookupParams[1].queryProperties.soapUrlProperties': null,
    'batchAdapterJobParams[0].queryProperties': null,
    'batchAdapterJobParams[0].previewCount': null,
    'batchAdapterJobParams[1].jobId': 'prefetch',
    'batchAdapterJobParams[1].schedule': '0 0/30 * * * ?',
    'batchAdapterJobParams[1].writePolicy': 'Overwrite',
    'batchAdapterJobParams[1].responseMeta.limit': 0,
    'batchAdapterJobParams[1].responseMeta.pageSize': 250,
    'batchAdapterJobParams[1].responseMeta.uniqueId': 'AgentID',
    'batchAdapterJobParams[1].responseMeta.responseAlias[0]': 'Name',
    'batchAdapterJobParams[1].responseMeta.responseAlias[1]': 'RemoteIPAddress',
    'batchAdapterJobParams[1].responseMeta.responseAlias[2]': 'MacAddress',
    'batchAdapterJobParams[1].responseMeta.responseAlias[3]': 'AgentID',
    'batchAdapterJobParams[1].lookupParams[0].id': 'criticalStep',
    'batchAdapterJobParams[1].lookupParams[0].urlProperties.url': '/api/v2/machines?iocscore_gte=1024&iocscore_lte=1024&per_page=${pageSize}&page=${page}',
    'batchAdapterJobParams[1].lookupParams[0].urlProperties.inputMeta': '',
    'batchAdapterJobParams[1].lookupParams[0].urlProperties.separator': null,
    'batchAdapterJobParams[1].lookupParams[0].urlProperties.uriMeta': 'Properties',
    'batchAdapterJobParams[1].lookupParams[0].body[0].mapper': '$.Items[*].Properties',
    'batchAdapterJobParams[1].lookupParams[0].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[1].lookupParams[0].body[0].responseMeta': '',
    'batchAdapterJobParams[1].lookupParams[0].body[0].rootResponseKey': null,
    'batchAdapterJobParams[1].lookupParams[0].header': null,
    'batchAdapterJobParams[1].lookupParams[0].additionalResponse': null,
    'batchAdapterJobParams[1].lookupParams[0].additionalParams': null,
    'batchAdapterJobParams[1].lookupParams[0].queryProperties': null,
    'batchAdapterJobParams[1].lookupParams[1].id': 'highStep',
    'batchAdapterJobParams[1].lookupParams[1].urlProperties.url': '/api/v2/machines?iocscore_gte=512&iocscore_lte=1023&per_page=${pageSize}&page=${page}',
    'batchAdapterJobParams[1].lookupParams[1].urlProperties.inputMeta': '',
    'batchAdapterJobParams[1].lookupParams[1].urlProperties.separator': null,
    'batchAdapterJobParams[1].lookupParams[1].urlProperties.uriMeta': 'Properties',
    'batchAdapterJobParams[1].lookupParams[1].body[0].mapper': '$.Items[*].Properties',
    'batchAdapterJobParams[1].lookupParams[1].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[1].lookupParams[1].body[0].responseMeta': '',
    'batchAdapterJobParams[1].lookupParams[1].body[0].rootResponseKey': null,
    'batchAdapterJobParams[1].lookupParams[1].header': null,
    'batchAdapterJobParams[1].lookupParams[1].additionalResponse': null,
    'batchAdapterJobParams[1].lookupParams[1].additionalParams': null,
    'batchAdapterJobParams[1].lookupParams[1].queryProperties': null,
    'batchAdapterJobParams[1].lookupParams[2].id': 'mediumStep',
    'batchAdapterJobParams[1].lookupParams[2].urlProperties.url': '/api/v2/machines?iocscore_gte=256&iocscore_lte=511&per_page=${pageSize}&page=${page}',
    'batchAdapterJobParams[1].lookupParams[2].urlProperties.inputMeta': '',
    'batchAdapterJobParams[1].lookupParams[2].urlProperties.separator': null,
    'batchAdapterJobParams[1].lookupParams[2].urlProperties.uriMeta': 'Properties',
    'batchAdapterJobParams[1].lookupParams[2].body[0].mapper': '$.Items[*].Properties',
    'batchAdapterJobParams[1].lookupParams[2].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[1].lookupParams[2].body[0].responseMeta': '',
    'batchAdapterJobParams[1].lookupParams[2].body[0].rootResponseKey': null,
    'batchAdapterJobParams[1].lookupParams[2].header': null,
    'batchAdapterJobParams[1].lookupParams[2].additionalResponse': null,
    'batchAdapterJobParams[1].lookupParams[2].additionalParams': null,
    'batchAdapterJobParams[1].lookupParams[2].queryProperties': null,
    'batchAdapterJobParams[1].lookupParams[3].id': 'lowStep',
    'batchAdapterJobParams[1].lookupParams[3].urlProperties.url': '/api/v2/machines?iocscore_lte=255&per_page=${pageSize}&page=${page}',
    'batchAdapterJobParams[1].lookupParams[3].urlProperties.inputMeta': '',
    'batchAdapterJobParams[1].lookupParams[3].urlProperties.separator': null,
    'batchAdapterJobParams[1].lookupParams[3].urlProperties.uriMeta': 'Properties',
    'batchAdapterJobParams[1].lookupParams[3].body[0].mapper': '$.Items[*].Properties',
    'batchAdapterJobParams[1].lookupParams[3].body[0].carryForwardMeta': '',
    'batchAdapterJobParams[1].lookupParams[3].body[0].responseMeta': '',
    'batchAdapterJobParams[1].lookupParams[3].body[0].rootResponseKey': null,
    'batchAdapterJobParams[1].lookupParams[3].header': null,
    'batchAdapterJobParams[1].lookupParams[3].additionalResponse': null,
    'batchAdapterJobParams[1].lookupParams[3].additionalParams': null,
    'batchAdapterJobParams[1].lookupParams[3].queryProperties': null,
    'batchAdapterJobParams[1].queryProperties': null,
    'batchAdapterJobParams[1].previewCount': null,
    'batchAdapterJobParams[2].jobId': 'flagging',
    'batchAdapterJobParams[2].schedule': null,
    'batchAdapterJobParams[2].writePolicy': null,
    'batchAdapterJobParams[2].responseMeta.limit': 0,
    'batchAdapterJobParams[2].responseMeta.pageSize': 250,
    'batchAdapterJobParams[2].responseMeta.uniqueId': null,
    'batchAdapterJobParams[2].responseMeta.responseAlias[0]': 'Severity',
    'batchAdapterJobParams[2].lookupParams': null,
    'batchAdapterJobParams[2].queryProperties': null,
    'batchAdapterJobParams[2].previewCount': null,
    'timeFilter': null
  },
  'createdOn': 0,
  'lastModifiedOn': 0
}];
