// Schema action types
export const SCHEMA_RETRIEVE = 'INVESTIGATE_FILES::SCHEMA_RETRIEVE';
export const FETCH_NEXT_FILES = 'INVESTIGATE_FILES::FETCH_NEXT_FILES';

// Filters
export const GET_FILTER = 'INVESTIGATE_FILES::GET_FILTER';
export const ADD_FILE_FILTER = 'INVESTIGATE_FILES::ADD_FILE_FILTER';
export const ADD_SYSTEM_FILTER = 'INVESTIGATE_FILES::ADD_SYSTEM_FILTER';
export const RESET_FILE_FILTERS = 'INVESTIGATE_FILES::RESET_FILE_FILTERS';
export const REMOVE_FILE_FILTER = 'INVESTIGATE_FILES::REMOVE_FILE_FILTER';
export const UPDATE_FILE_FILTER = 'INVESTIGATE_FILES::UPDATE_FILE_FILTER';

// UI action types
export const SET_SORT_BY = 'INVESTIGATE_FILES::SET_SORT_BY';
export const RESET_FILES = 'INVESTIGATE_FILES::RESET_FILES';
export const INCREMENT_PAGE_NUMBER = 'INVESTIGATE_FILES::INCREMENT_PAGE_NUMBER';
export const SET_ACTIVE_FILTER = 'INVESTIGATE_FILES::SET_ACTIVE_FILTER';
export const DOWNLOAD_FILE_AS_CSV = 'INVESTIGATE_FILES::DOWNLOAD_FILE_AS_CSV';
export const UPDATE_COLUMN_VISIBILITY = 'INVESTIGATE_FILES::UPDATE_COLUMN_VISIBILITY';
export const RESET_DOWNLOAD_ID = 'INVESTIGATE_FILES::RESET_DOWNLOAD_ID';

export const SET_EXPRESSION_LIST = 'INVESTIGATE_FILES::SET_EXPRESSION_LIST';
export const UPDATE_FILTER_LIST = 'INVESTIGATE_FILES::UPDATE_FILTER_LIST';
export const SET_APPLIED_FILES_FILTER = 'INVESTIGATE_FILES::SET_APPLIED_FILES_FILTER';
export const SET_SYSTEM_FILTER_FLAG = 'INVESTIGATE_FILES::SET_SYSTEM_FILTER_FLAG';
