// Incidents Action Types
export const FETCH_INCIDENTS_STARTED = 'RESPOND::FETCH_INCIDENTS_STARTED';
export const FETCH_INCIDENTS_STREAM_INITIALIZED = 'RESPOND::FETCH_INCIDENTS_STREAM_INITIALIZED';
export const FETCH_INCIDENTS_COMPLETED = 'RESPOND::FETCH_INCIDENTS_STREAM_COMPLETED';
export const FETCH_INCIDENTS_ERROR = 'RESPOND::FETCH_INCIDENTS_ERROR';
export const FETCH_INCIDENTS_RETRIEVE_BATCH = 'RESPOND::FETCH_INCIDENTS_RETRIEVE_BATCH';
export const FETCH_INCIDENTS_TOTAL_COUNT = 'RESPOND::FETCH_INCIDENTS_TOTAL_COUNT';
export const FETCH_INCIDENT_DETAILS = 'RESPOND::FETCH_INCIDENT_DETAILS';
export const FETCH_INCIDENT_STORYLINE = 'RESPOND::FETCH_INCIDENT_STORYLINE';
export const UPDATE_INCIDENT_FILTERS = 'RESPOND::UPDATE_INCIDENT_FILTERS';
export const RESET_INCIDENT_FILTERS = 'RESPOND::RESET_INCIDENT_FILTERS';

export const FETCH_STATUS_TYPES = 'RESPOND::FETCH_STATUS_TYPES';
export const FETCH_PRIORITY_TYPES = 'RESPOND::FETCH_PRIORITY_TYPES';
export const FETCH_CATEGORY_TAGS = 'RESPOND::FETCH_CATEGORY_TAGS';


/* Remediation Tasks */
export const FETCH_REMEDIATION_TASKS = 'RESPOND::FETCH_REMEDIATION_TASKS';
export const UPDATE_REMEDIATION_TASK_FILTERS = 'RESPOND::UPDATE_REMEDIATION_TASK_FILTERS';
export const FETCH_REMEDIATION_TASKS_TOTAL_COUNT = 'RESPOND::FETCH_REMEDIATION_TASKS_TOTAL_COUNT';
export const CREATE_REMEDIATION_TASK = 'RESPOND::CREATE_REMEDIATION_TASK';
export const TOGGLE_FILTER_PANEL_REMEDIATION_TASKS = 'RESPOND::TOGGLE_FILTER_PANEL_REMEDIATION_TASKS';
export const RESET_REMEDIATION_TASK_FILTERS = 'RESPOND::RESET_REMEDIATION_TASK_FILTERS';
export const TOGGLE_REMEDIATION_TASKS_CUSTOM_DATE_RESTRICTION = 'RESPOND::TOGGLE_REMEDIATION_TASKS_CUSTOM_DATE_RESTRICTION';
export const TOGGLE_REMEDIATION_TASK_SELECTED = 'RESPOND::TOGGLE_REMEDIATION_TASK_SELECTED';
export const TOGGLE_FOCUS_REMEDIATION_TASK = 'RESPOND::TOGGLE_FOCUS_REMEDIATION_TASK';
export const CLEAR_FOCUS_REMEDIATION_TASK = 'RESPOND::CLEAR_FOCUS_REMEDIATION_TASK';
export const TOGGLE_SELECT_ALL_REMEDIATION_TASKS = 'RESPOND::TOGGLE_SELECT_ALL_REMEDIATION_TASK';
export const REMEDIATION_TASK_SORT_BY = 'RESPOND::REMEDIATION_TASK_SORT_BY';

export const UPDATE_INCIDENT = 'RESPOND::UPDATE_INCIDENT';

export const FETCH_ALL_USERS = 'RESPOND::FETCH_ALL_USERS';

export const CREATE_JOURNAL_ENTRY = 'RESPOND::CREATE_JOURNAL_ENTRY';
export const DELETE_JOURNAL_ENTRY = 'RESPOND::DELETE_JOURNAL_ENTRY';
export const UPDATE_JOURNAL_ENTRY = 'RESPOND::UPDATE_JOURNAL_ENTRY';

export const SORT_BY = 'RESPOND::SORT_BY';

export const INITIALIZE_INCIDENT = 'RESPOND::INITIALIZE_INCIDENT';

// UI State Action Types
export const TOGGLE_FILTER_PANEL = 'RESPOND::TOGGLE_FILTER_PANEL';
export const TOGGLE_THEME = 'RESPOND::TOGGLE_THEME';
export const TOGGLE_INCIDENT_SELECTED = 'RESPOND::TOGGLE_INCIDENT_SELECTED';
export const TOGGLE_SELECT_MODE = 'RESPOND::TOGGLE_SELECT_MODE';
export const CLEAR_SELECTED_INCIDENTS = 'RESPOND::CLEAR_SELECTED_INCIDENTS';
export const UPDATE_SELECTED_CANNED_FILTER = 'RESPOND::UPDATE_SELECTED_CANNED_FILTER';
export const TOGGLE_CUSTOM_DATE_RESTRICTION = 'RESPOND::TOGGLE_CUSTOM_DATE_RESTRICTION';

export const TOGGLE_JOURNAL_PANEL = 'RESPOND::TOGGLE_JOURNAL_PANEL';
export const SET_VIEW_MODE = 'RESPOND::SET_VIEW_MODE';
export const RESIZE_INCIDENT_INSPECTOR = 'RESPOND::RESIZE_INCIDENT_INSPECTOR';

export const SET_INCIDENT_SELECTION = 'RESPOND::SET_INCIDENT_SELECTION';
export const TOGGLE_INCIDENT_SELECTION = 'RESPOND::TOGGLE_INCIDENT_SELECTION';
export const TOGGLE_FOCUS_INCIDENT = 'RESPOND::TOGGLE_FOCUS_INCIDENT';