// Data Retrieval Related Action Types
export const FETCH_INCIDENTS = 'RESPOND::FETCH_INCIDENTS';
export const FETCH_INCIDENT_DETAILS = 'RESPOND::FETCH_INCIDENT_DETAILS';
export const FETCH_INCIDENT_STORYLINE = 'RESPOND::FETCH_INCIDENT_STORYLINE';
export const UPDATE_INCIDENT_FILTERS = 'RESPOND::UPDATE_INCIDENT_FILTERS';
export const SORT_BY = 'RESPOND::SORT_BY';

// UI State Action Types
export const TOGGLE_FILTER_PANEL = 'RESPOND::TOGGLE_FILTER_PANEL';
export const TOGGLE_THEME = 'RESPOND::TOGGLE_THEME';
export const TOGGLE_INCIDENT_SELECTED = 'RESPOND::TOGGLE_INCIDENT_SELECTED';
export const TOGGLE_SELECT_MODE = 'RESPOND::TOGGLE_SELECT_MODE';
export const CLEAR_SELECTED_INCIDENTS = 'RESPOND::CLEAR_SELECTED_INCIDENTS';
export const UPDATE_SELECTED_CANNED_FILTER = 'RESPOND::UPDATE_SELECTED_CANNED_FILTER';