// Incidents Action Types
export const FETCH_INCIDENTS_STARTED = 'RESPOND::FETCH_INCIDENTS_STARTED';
export const FETCH_INCIDENTS_STREAM_INITIALIZED = 'RESPOND::FETCH_INCIDENTS_STREAM_INITIALIZED';
export const FETCH_INCIDENTS_COMPLETED = 'RESPOND::FETCH_INCIDENTS_STREAM_COMPLETED';
export const FETCH_INCIDENTS_ERROR = 'RESPOND::FETCH_INCIDENTS_ERROR';
export const FETCH_INCIDENTS_RETRIEVE_BATCH = 'RESPOND::FETCH_INCIDENTS_RETRIEVE_BATCH';
export const FETCH_INCIDENTS_TOTAL_COUNT = 'RESPOND::FETCH_INCIDENTS_TOTAL_COUNT';
export const FETCH_INCIDENT_DETAILS = 'RESPOND::FETCH_INCIDENT_DETAILS';
export const FETCH_INCIDENT_STORYLINE_STARTED = 'RESPOND::FETCH_INCIDENT_STORYLINE_STARTED';
export const FETCH_INCIDENT_STORYLINE_STREAM_INITIALIZED = 'RESPOND::FETCH_INCIDENT_STORYLINE_STREAM_INITIALIZED';
export const FETCH_INCIDENT_STORYLINE_COMPLETED = 'RESPOND::FETCH_INCIDENT_STORYLINE_COMPLETED';
export const FETCH_INCIDENT_STORYLINE_ERROR = 'RESPOND::FETCH_INCIDENT_STORYLINE_ERROR';
export const FETCH_INCIDENT_STORYLINE_RETRIEVE_BATCH = 'RESPOND::FETCH_INCIDENT_STORYLINE_RETRIEVE_BATCH';
export const FETCH_INCIDENT_STORYLINE_EVENTS_STREAM_INITIALIZED = 'RESPOND::FETCH_INCIDENT_STORYLINE_EVENTS_STREAM_INITIALIZED';
export const FETCH_INCIDENT_STORYLINE_EVENTS_REQUEST_BATCH = 'RESPOND::FETCH_INCIDENT_STORYLINE_EVENTS_REQUEST_BATCH';
export const FETCH_INCIDENT_STORYLINE_EVENTS_RETRIEVE_BATCH = 'RESPOND::FETCH_INCIDENT_STORYLINE_EVENTS_RETRIEVE_BATCH';
export const FETCH_INCIDENT_STORYLINE_EVENTS_COMPLETED = 'RESPOND::FETCH_INCIDENT_STORYLINE_EVENTS_COMPLETED';
export const FETCH_INCIDENT_STORYLINE_EVENTS_ERROR = 'RESPOND::FETCH_INCIDENT_STORYLINE_EVENTS_ERROR';
export const UPDATE_INCIDENT_FILTERS = 'RESPOND::UPDATE_INCIDENT_FILTERS';
export const RESET_INCIDENT_FILTERS = 'RESPOND::RESET_INCIDENT_FILTERS';
export const TOGGLE_SELECT_ALL_INCIDENTS = 'RESPOND::TOGGLE_SELECT_ALL_INCIDENTS';
export const CLEAR_FOCUS_INCIDENTS = 'RESPOND::CLEAR_FOCUS_INCIDENTS';
export const UPDATE_INCIDENT = 'RESPOND::UPDATE_INCIDENT';
export const DELETE_INCIDENT = 'RESPOND::DELETE_INCIDENT';
export const FETCH_REMEDIATION_TASKS_FOR_INCIDENT = 'RESPOND::FETCH_REMEDIATION_TASKS_FOR_INCIDENT';
export const SET_TASKS_JOURNAL_MODE = 'RESPOND::SET_TASKS_JOURNAL_MODE';
export const TOGGLE_TASKS_JOURNAL = 'RESPOND::TOGGLE_TASKS_JOURNAL';
export const CREATE_INCIDENT_SAGA = 'RESPOND::CREATE_INCIDENT::SAGA';
export const CREATE_INCIDENT = 'RESPOND::CREATE_INCIDENT';
export const START_TRANSACTION = 'RESPOND::START_TRANSACTION';
export const FINISH_TRANSACTION = 'RESPOND::FINISH_TRANSACTION';

export const FETCH_STATUS_TYPES = 'RESPOND::FETCH_STATUS_TYPES';
export const FETCH_PRIORITY_TYPES = 'RESPOND::FETCH_PRIORITY_TYPES';
export const FETCH_CATEGORY_TAGS = 'RESPOND::FETCH_CATEGORY_TAGS';

export const SORT_BY = 'RESPOND::SORT_BY';
export const INITIALIZE_INCIDENT = 'RESPOND::INITIALIZE_INCIDENT';

/* Remediation Tasks */
export const FETCH_REMEDIATION_TASKS = 'RESPOND::FETCH_REMEDIATION_TASKS';
export const UPDATE_REMEDIATION_TASK = 'RESPOND::UPDATE_REMEDIATION_TASK';
export const UPDATE_REMEDIATION_TASK_FILTERS = 'RESPOND::UPDATE_REMEDIATION_TASK_FILTERS';
export const FETCH_REMEDIATION_TASKS_TOTAL_COUNT = 'RESPOND::FETCH_REMEDIATION_TASKS_TOTAL_COUNT';
export const CREATE_REMEDIATION_TASK = 'RESPOND::CREATE_REMEDIATION_TASK';
export const TOGGLE_FILTER_PANEL_REMEDIATION_TASKS = 'RESPOND::TOGGLE_FILTER_PANEL_REMEDIATION_TASKS';
export const RESET_REMEDIATION_TASK_FILTERS = 'RESPOND::RESET_REMEDIATION_TASK_FILTERS';
export const TOGGLE_REMEDIATION_TASKS_CUSTOM_DATE_RESTRICTION = 'RESPOND::TOGGLE_REMEDIATION_TASKS_CUSTOM_DATE_RESTRICTION';
export const TOGGLE_REMEDIATION_TASK_SELECTED = 'RESPOND::TOGGLE_REMEDIATION_TASK_SELECTED';
export const TOGGLE_FOCUS_REMEDIATION_TASK = 'RESPOND::TOGGLE_FOCUS_REMEDIATION_TASK';
export const CLEAR_FOCUS_REMEDIATION_TASK = 'RESPOND::CLEAR_FOCUS_REMEDIATION_TASK';
export const TOGGLE_SELECT_ALL_REMEDIATION_TASKS = 'RESPOND::TOGGLE_SELECT_ALL_REMEDIATION_TASK';
export const REMEDIATION_TASK_SORT_BY = 'RESPOND::REMEDIATION_TASK_SORT_BY';
export const FETCH_REMEDIATION_STATUS_TYPES = 'RESPOND::FETCH_REMEDIATION_STATUS_TYPES';
export const FETCH_REMEDIATION_TYPES = 'RESPOND::FETCH_REMEDIATION_TYPES';
export const DELETE_REMEDIATION_TASK = 'RESPOND::DELETE_REMEDIATION_TASK';

/* Alerts */
export const FETCH_ALERTS_STARTED = 'RESPOND::FETCH_ALERTS_STARTED';
export const FETCH_ALERTS_STREAM_INITIALIZED = 'RESPOND::FETCH_ALERTS_STREAM_INITIALIZED';
export const FETCH_ALERTS_COMPLETED = 'RESPOND::FETCH_ALERTS_COMPLETED';
export const FETCH_ALERTS_ERROR = 'RESPOND::FETCH_ALERTS_ERROR';
export const FETCH_ALERTS_RETRIEVE_BATCH = 'RESPOND::FETCH_ALERTS_RETRIEVE_BATCH';
export const FETCH_ALERTS_TOTAL_COUNT = 'RESPOND::FETCH_ALERTS_TOTAL_COUNT';
export const UPDATE_ALERT = 'RESPOND::UPDATE_ALERT';
export const DELETE_ALERT = 'RESPOND::DELETE_ALERT';
export const UPDATE_ALERT_FILTERS = 'RESPOND::UPDATE_ALERT_FILTERS';
export const TOGGLE_FILTER_PANEL_ALERTS = 'RESPOND::TOGGLE_FILTER_PANEL_ALERTS';
export const RESET_ALERT_FILTERS = 'RESPOND::RESET_ALERT_FILTERS';
export const TOGGLE_ALERTS_CUSTOM_DATE_RESTRICTION = 'RESPOND::TOGGLE_ALERT_CUSTOM_DATE_RESTRICTION';
export const TOGGLE_ALERT_SELECTED = 'RESPOND::TOGGLE_ALERT_SELECTED';
export const TOGGLE_FOCUS_ALERT = 'RESPOND::TOGGLE_FOCUS_ALERT';
export const CLEAR_FOCUS_ALERT = 'RESPOND::CLEAR_FOCUS_ALERT';
export const TOGGLE_SELECT_ALL_ALERTS = 'RESPOND::TOGGLE_SELECT_ALL_ALERTS';
export const ALERT_SORT_BY = 'RESPOND::ALERT_SORT_BY';
export const FETCH_ALERT_SOURCES = 'RESPOND::FETCH_ALERT_SOURCES';
export const FETCH_ALERT_TYPES = 'RESPOND::FETCH_ALERT_TYPES';
export const FETCH_ORIGINAL_ALERT = 'RESPOND::FETCH_ORIGINAL_ALERT';
export const FETCH_ALERT_NAMES = 'RESPOND::FETCH_ALERT_NAMES';

export const ALERTS_UPDATE_SEARCH_INCIDENTS_TEXT = 'RESPOND::ALERTS_UPDATE_SEARCH_INCIDENTS_TEXT';
export const ALERTS_UPDATE_SEARCH_INCIDENTS_SORTBY = 'RESPOND::ALERTS_UPDATE_SEARCH_INCIDENTS_SORTBY';
export const ALERTS_SEARCH_INCIDENTS_SELECT = 'RESPOND::ALERTS_SEARCH_INCIDENTS_SELECT';
export const ALERTS_SEARCH_INCIDENTS_STARTED = 'RESPOND::ALERTS_SEARCH_INCIDENTS_STARTED';
export const ALERTS_SEARCH_INCIDENTS_STREAM_INITIALIZED = 'RESPOND::ALERTS_SEARCH_INCIDENTS_STREAM_INITIALIZED';
export const ALERTS_SEARCH_INCIDENTS_COMPLETED = 'RESPOND::ALERTS_SEARCH_INCIDENTS_COMPLETED';
export const ALERTS_SEARCH_INCIDENTS_RETRIEVE_BATCH = 'RESPOND::ALERTS_SEARCH_INCIDENTS_RETRIEVE_BATCH';
export const ALERTS_SEARCH_INCIDENTS_ERROR = 'RESPOND::ALERTS_SEARCH_INCIDENTS_ERROR';
export const ALERTS_ADD_TO_INCIDENT = 'RESPOND::ALERTS_ADD_TO_INCIDENT';

export const CLEAR_SEARCH_INCIDENTS_RESULTS_FOR_ALERTS = 'RESPOND::CLEAR_SEARCH_INCIDENTS_RESULTS_FOR_ALERTS';

/* Alert Details */
export const INITIALIZE_ALERT = 'RESPOND::INITIALIZE_ALERT';
export const RESIZE_ALERT_INSPECTOR = 'RESPOND::RESIZE_ALERT_INSPECTOR';
export const FETCH_ALERT_DETAILS_STARTED = 'RESPOND::FETCH_ALERT_DETAILS_STARTED';
export const FETCH_ALERT_DETAILS_STREAM_INITIALIZED = 'RESPOND::FETCH_ALERT_DETAILS_STREAM_INITIALIZED';
export const FETCH_ALERT_DETAILS_RETRIEVE_BATCH = 'RESPOND::FETCH_ALERT_DETAILS_RETRIEVE_BATCH';
export const FETCH_ALERT_DETAILS_COMPLETED = 'RESPOND::FETCH_ALERT_DETAILS_COMPLETED';
export const FETCH_ALERT_DETAILS_ERROR = 'RESPOND::FETCH_ALERT_DETAILS_ERROR';
export const FETCH_ALERT_EVENTS = 'RESPOND::FETCH_ALERT_EVENTS';

/* Users */
export const FETCH_ALL_ENABLED_USERS = 'RESPOND::FETCH_ALL_ENABLED_USERS';
export const FETCH_ALL_USERS = 'RESPOND::FETCH_ALL_USERS';

/* Journal */
export const FETCH_MILESTONE_TYPES = 'RESPOND::FETCH_MILESTONE_TYPES';
export const CREATE_JOURNAL_ENTRY = 'RESPOND::CREATE_JOURNAL_ENTRY';
export const DELETE_JOURNAL_ENTRY = 'RESPOND::DELETE_JOURNAL_ENTRY';
export const UPDATE_JOURNAL_ENTRY = 'RESPOND::UPDATE_JOURNAL_ENTRY';

/* Search for Related Indicators */
export const SET_DEFAULT_SEARCH_TIME_FRAME_NAME = 'RESPOND::SET_DEFAULT_SEARCH_TIME_FRAME_NAME';
export const SET_DEFAULT_SEARCH_ENTITY_TYPE = 'RESPOND::SET_DEFAULT_SEARCH_ENTITY_TYPE';
export const SEARCH_RELATED_INDICATORS_STARTED = 'RESPOND::SEARCH_RELATED_INDICATORS_STARTED';
export const SEARCH_RELATED_INDICATORS_STREAM_INITIALIZED = 'RESPOND::SEARCH_RELATED_INDICATORS_STREAM_INITIALIZED';
export const SEARCH_RELATED_INDICATORS_COMPLETED = 'RESPOND::SEARCH_RELATED_INDICATORS_COMPLETED';
export const SEARCH_RELATED_INDICATORS_ERROR = 'RESPOND::SEARCH_RELATED_INDICATORS_ERROR';
export const SEARCH_RELATED_INDICATORS_STOPPED = 'RESPOND::SEARCH_RELATED_INDICATORS_STOPPED';
export const SEARCH_RELATED_INDICATORS_RETRIEVE_BATCH = 'RESPOND::SEARCH_RELATED_INDICATORS_RETRIEVE_BATCH';
export const ADD_RELATED_INDICATORS = 'RESPOND::ADD_RELATED_INDICATORS';
export const CLEAR_ADD_RELATED_INDICATORS_STATUS = 'RESPOND:CLEAR_ADD_RELATED_INDICATORS_STATUS';

/* Aggregation Rules */
export const NEW_AGGREGATION_RULE = 'RESPOND::NEW_AGGREGATION_RULE';
export const FETCH_AGGREGATION_RULES_SAGA = 'RESPOND::FETCH_AGGREGATION_RULES::SAGA';
export const FETCH_AGGREGATION_RULES_STARTED = 'RESPOND::FETCH_AGGREGATION_RULES_STARTED';
export const FETCH_AGGREGATION_RULES_FAILED = 'RESPOND::FETCH_AGGREGATION_RULES_FAILED';
export const FETCH_AGGREGATION_RULES = 'RESPOND::FETCH_AGGREGATION_RULES';
export const FETCH_AGGREGATION_RULE_SAGA = 'RESPOND::FETCH_AGGREGATION_RULE::SAGA';
export const FETCH_AGGREGATION_RULE_STARTED = 'RESPOND::FETCH_AGGREGATION_RULE_STARTED';
export const FETCH_AGGREGATION_RULE_FAILED = 'RESPOND::FETCH_AGGREGATION_RULE_FAILED';
export const FETCH_AGGREGATION_RULE = 'RESPOND::FETCH_AGGREGATION_RULE';
export const FETCH_AGGREGATION_FIELDS_SAGA = 'RESPOND::FETCH_AGGREGATION_FIELDS::SAGA';
export const FETCH_AGGREGATION_FIELDS_STARTED = 'RESPOND::FETCH_AGGREGATION_FIELDS_STARTED';
export const FETCH_AGGREGATION_FIELDS_FAILED = 'RESPOND::FETCH_AGGREGATION_FIELDS_FAILED';
export const FETCH_AGGREGATION_FIELDS = 'RESPOND::FETCH_AGGREGATION_FIELDS';
export const AGGREGATION_RULES_ADD_CONDITION = 'RESPOND::AGGREGATION_RULES_ADD_CONDITION';
export const AGGREGATION_RULES_REMOVE_CONDITION = 'RESPOND::AGGREGATION_RULES_REMOVE_CONDITION';
export const AGGREGATION_RULES_ADD_GROUP = 'RESPOND::AGGREGATION_RULES_ADD_GROUP';
export const AGGREGATION_RULES_REMOVE_GROUP = 'RESPOND::AGGREGATION_RULES_REMOVE_GROUP';
export const AGGREGATION_RULES_UPDATE_CONDITION = 'RESPOND::AGGREGATION_RULES_UPDATE_CONDITION';
export const AGGREGATION_RULES_UPDATE_GROUP = 'RESPOND::AGGREGATION_RULES_UPDATE_GROUP';
export const AGGREGATION_RULES_SELECT_RULE = 'RESPOND::AGGREGATION_RULES_SELECT_RULE';
export const AGGREGATION_RULES_DELETE_SAGA = 'RESPOND::AGGREGATION_RULES_DELETE::SAGA';
export const AGGREGATION_RULES_DELETE_STARTED = 'RESPOND::AGGREGATION_RULES_DELETE_STARTED';
export const AGGREGATION_RULES_DELETE = 'RESPOND::AGGREGATION_RULES_DELETE';
export const AGGREGATION_RULES_DELETE_FAILED = 'RESPOND::AGGREGATION_RULES_DELETE_FAILED';
export const AGGREGATION_RULES_REORDER_SAGA = 'RESPOND::AGGREGATION_RULES_REORDER::SAGA';
export const AGGREGATION_RULES_REORDER_STARTED = 'RESPOND::AGGREGATION_RULES_REORDER_STARTED';
export const AGGREGATION_RULES_REORDER = 'RESPOND::AGGREGATION_RULES_REORDER';
export const AGGREGATION_RULES_REORDER_FAILED = 'RESPOND::AGGREGATION_RULES_REORDER_FAILED';
export const AGGREGATION_RULES_CLONE_SAGA = 'RESPOND::AGGREGATION_RULES_CLONE::SAGA';
export const AGGREGATION_RULES_CLONE_STARTED = 'RESPOND::AGGREGATION_RULES_CLONE_STARTED';
export const AGGREGATION_RULES_CLONE = 'RESPOND::AGGREGATION_RULES_CLONE';
export const AGGREGATION_RULES_CLONE_FAILED = 'RESPOND::AGGREGATION_RULES_CLONE_FAILED';
export const AGGREGATION_RULES_UPDATE_INFO = 'RESPOND::AGGREGATION_RULES_UPDATE_INFO';
export const AGGREGATION_RULES_CLEAR_MATCH_CONDITIONS = 'RESPOND::AGGREGATION_RULES_CLEAR_MATCH_CONDITIONS';
export const SAVE_AGGREGATION_RULE_SAGA = 'RESPOND::SAVE_AGGREGATION_RULE::SAGA';
export const AGGREGATION_RULES_SAVE_STARTED = 'RESPOND::AGGREGATION_RULES_SAVE_STARTED';
export const AGGREGATION_RULES_SAVE = 'RESPOND::AGGREGATION_RULES_SAVE';
export const AGGREGATION_RULES_SAVE_FAILED = 'RESPOND::AGGREGATION_RULES_SAVE_FAILED';
export const CREATE_AGGREGATION_RULE_SAGA = 'RESPOND::CREATE_AGGREGATION_RULE::SAGA';
export const CREATE_AGGREGATION_RULE_STARTED = 'RESPOND::CREATE_AGGREGATION_RULE_STARTED';
export const CREATE_AGGREGATION_RULE = 'RESPOND::CREATE_AGGREGATION_RULE';
export const CREATE_AGGREGATION_RULE_FAILED = 'RESPOND::CREATE_AGGREGATION_RULE_FAILED';

// UI State Action Types
export const TOGGLE_FILTER_PANEL = 'RESPOND::TOGGLE_FILTER_PANEL';
export const TOGGLE_INCIDENT_SELECTED = 'RESPOND::TOGGLE_INCIDENT_SELECTED';
export const TOGGLE_CUSTOM_DATE_RESTRICTION = 'RESPOND::TOGGLE_CUSTOM_DATE_RESTRICTION';

export const SET_HIDE_VIZ = 'RESPOND::SET_HIDE_VIZ';
export const SET_VIEW_MODE = 'RESPOND::SET_VIEW_MODE';
export const RESIZE_INCIDENT_INSPECTOR = 'RESPOND::RESIZE_INCIDENT_INSPECTOR';

export const CLEAR_INCIDENT_SELECTION = 'RESPOND::CLEAR_INCIDENT_SELECTION';
export const SET_INCIDENT_SELECTION = 'RESPOND::SET_INCIDENT_SELECTION';
export const TOGGLE_INCIDENT_SELECTION = 'RESPOND::TOGGLE_INCIDENT_SELECTION';
export const TOGGLE_FOCUS_INCIDENT = 'RESPOND::TOGGLE_FOCUS_INCIDENT';
