const CONST = {
  COLLAPSE_ICON_SIZE: 16,
  COUNT_SPACING: 2,
  SPACING: 15,
  NODE_WIDTH: 130,
  NODE_HEIGHT: 80,
  NODE_SEPARATION: 5.75,
  LINK_HEIGHT: 250,
  LINK_WIDTH: 30,
  RADIUS: 10,
  DURATION: 750
};

const DISTANCE = {
  ICON_Y: -10,
  ICON_X: -10,
  PROCESS_TYPE_Y: -5,
  PROCESS_TYPE_X: 17,
  SCORE_Y: -20,
  SCORE_X: -40,
  MACHINE_COUNT_Y: 10,
  ICON_WIDTH: 19
};

export {
  CONST,
  DISTANCE
};