export const SET_EVENTS = 'PROCESS_ANALYSIS::SET_EVENTS';
export const SET_PROCESS_ANALYSIS_INPUT = 'PROCESS_ANALYSIS::SET_PROCESS_ANALYSIS_INPUT';
export const COMPLETED_EVENTS_STREAMING = 'PROCESS_ANALYSIS::COMPLETED_EVENTS_STREAMING';
export const INIT_EVENTS_STREAMING = 'PROCESS_ANALYSIS::INIT_EVENTS_STREAMING';
export const SET_EVENTS_PAGE_ERROR = 'PROCESS_ANALYSIS::SET_EVENTS_PAGE_ERROR';
