package fortscale.domain.lastoccurrenceinstant.store;

import fortscale.domain.lastoccurrenceinstant.reader.LastOccurrenceInstantReader;
import fortscale.domain.lastoccurrenceinstant.writer.LastOccurrenceInstantWriter;

public interface LastOccurrenceInstantStore extends LastOccurrenceInstantReader, LastOccurrenceInstantWriter {}
